"""The read-only Bash guard denies git worktree, index, and ref moves, denies
shell input it cannot read, passes every read through, and refuses loudly
rather than run blind when the hook payload is not what it expects."""

from __future__ import annotations

import io
import json
import subprocess
import sys
import unittest
from contextlib import redirect_stdout
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import readonly_bash_guard as guard  # noqa: E402

DENIED = (
    "git stash",
    "git stash list",
    "git -C /tmp/v checkout -- a.py",
    "cd /tmp/v && git reset --hard HEAD~1",
    "/usr/bin/git apply patch.diff",
    "git -c core.pager=cat restore scripts/a.py",
    "git --no-pager switch main",
    "git log -1 ; git clean -fd",
    "git add -A && git commit -m x",
    "git --git-dir /tmp/v/.git --work-tree /tmp/v checkout -- a.py",
    "git pull --rebase origin main",
    "bash -lc 'git reset --hard'",
    "sh -c \"cd /tmp/v && git checkout -- a.py\"",
    "eval 'git stash'",
    "bash -c 'bash -c \"git restore a.py\"'",
    "ssh host 'git reset --hard'",
    "xargs -I{} sh -c 'git checkout -- {}'",
    "git fetch origin",
    "git update-index --assume-unchanged a.py",
    "git update-ref -d refs/heads/tmp",
    "git branch -D tmp",
    "git branch feature",
    "git tag v1",
    "git tag -d v1",
    "git reflog expire --all",
    "git remote add mirror /tmp/x",
    "git log -1; git bisect start",
    "$(git stash)",
    "LOG=$(git reset --hard)",
    "`git checkout -- a.py`",
    "(git reset --hard)",
    "{ git reset --hard; }",
    "sudo git reset --hard",
    "env GIT_DIR=.git git reset --hard",
    "timeout 30s git clean -fd",
    "find . -name '*.py' -exec git rm {} \\;",
    "cd /tmp/v\ngit reset --hard",
    "bash <<'EOF'\ngit reset --hard\nEOF",
    "if git stash; then echo x; fi",
    'echo "$(git stash)"',
    'CMD="git reset --hard"; eval "$CMD"',
    "eval $CMD",
    'bash -c "$SCRIPT"',
    'sh -c "$(cat x.sh)"',
    "bash /tmp/x.sh",
    "source ./x.sh",
    ". ./x.sh",
    "bash <(cat x.sh)",
    "ssh host \"$CMD\"",
    "python3 -c \"import subprocess; subprocess.run(['git', 'reset', '--hard'])\"",
    "python3 - <<'EOF'\nimport subprocess\nsubprocess.run(['git', 'stash'])\nEOF",
    "python3 -c 'import os; os.system(\"git checkout -- a.py\")'",
    "CMD=reset; git $CMD --hard",
    "$GIT reset --hard",
    "$(which git) reset --hard",
    "printf 'git reset --hard\\n' | bash",
    "echo 'git reset --hard' | bash",
    "cat script.sh | bash",
    "bash < script.sh",
    "bash -s < script.sh",
    "sh -s",
    "env -u GIT_INDEX_FILE git reset --hard",
    "sudo -u root git reset --hard",
    "git \\\nreset --hard",
    "sed -i 's/foo/bar/' scripts/_git.py",
    "perl -pi -e 's/a/b/' scripts/_git.py",
    "cp /tmp/backup.py scripts/_git.py",
    "mv scripts/a.py scripts/b.py",
    "rm -f scripts/_git.py",
    "echo bogus > scripts/_git.py",
    "echo 'git reset --hard' >> notes.md",
    "cat > f.py <<'EOF'\nDENIED = (\"git stash\", 'git restore a.py')\nEOF",
    "cat /tmp/x | tee scripts/_git.py",
    "dd if=/dev/zero of=scripts/_git.py",
    "truncate -s0 scripts/_git.py",
    "patch -p1 < /tmp/fix.diff",
    "touch scripts/new.py",
    "mkdir -p tmp/scratch",
    "chmod +x scripts/x.py",
    "cd scripts && printf 'x' > y.py",
    "sudo cp /tmp/x scripts/x.py",
    "python3 -c 'import os; os.system(\"git reset --hard\")'",
    "git log;git reset --hard",
    "git log&&git checkout -- .",
    "git log -1|xargs git stash",
    "git diff --output=patch.diff",
    "git diff --output patch.diff HEAD~1",
    "git archive -o out.tar HEAD",
    "git clone /tmp/src clone",
    "git format-patch -1 -o patches",
    "git config user.name someone",
    "git config --unset user.name",
    "git symbolic-ref HEAD refs/heads/x",
    "git lfs pull",
    "git sparse-checkout set scripts",
    "git maintenance run",
    "/usr/bin/env git reset --hard",
    "/usr/bin/sudo git reset --hard",
    "/usr/bin/timeout 5 git reset --hard",
    '/usr/bin/env bash -c "git reset --hard"',
    "perl -e 'system(\"git reset --hard\")'",
    "ruby -e 'system(\"git reset --hard\")'",
    "php -r 'system(\"git reset --hard\");'",
    "python3 -c 'from os import system; system(\"git reset --hard\")'",
    "rm -f scripts/x.py 2>/dev/null",
    "echo bogus >| scripts/_git.py",
    "find scripts -name '*.py' -exec rm {} \\;",
    "find . -name '*.pyc' -delete",
    "find scripts -exec sed -i 's/a/b/' {} \\;",
    "git ls-files | xargs rm",
    "git ls-files '*.py' | xargs sed -i 's/a/b/'",
    "cp -- /tmp/a -oscripts/a.py",
    "echo bad > {}",
    'bash -c "echo bad > {}"',
    "find scripts -exec bash -c 'echo bad > {}' {} \\;",
    "cp scripts/x.py{,.bak}",
    "chmod -w scripts/x.py",
    "chmod 644 scripts/x.py",
    "chmod u+x scripts/x.py",
    "git {reset,stash} --hard",
    "git {branch,tag} -D tmp",
    "find scripts -exec git {reset,stash} {} \\;",
    "cp {/tmp/a.py,scripts/b.py}",
    "mv scripts/{a,b}.py /tmp/",
    "rm scripts/x{1..3}.py",
    "caffeinate git reset --hard",
    "stdbuf -o0 git reset --hard",
    "watch -n1 git reset --hard",
    "doas git reset --hard",
    "flock /tmp/lock git reset --hard",
    "setsid git reset --hard",
    "caffeinate rm scripts/x.py",
    "./run.sh git reset --hard",
    "watch -n1 'git reset --hard'",
    "flock -c 'git reset --hard' /tmp/lock",
    "timeout 30 'git reset --hard'",
    "my_tool 'echo x > scripts/a.py'",
    "watch -n1 \"$CMD\"",
    "find scripts -exec sudo rm {} \\;",
    "find scripts -exec env rm {} \\;",
    "find scripts -name '*.py' -exec nice rm {} \\;",
    "find scripts -exec timeout 5 tee {} \\;",
    "find scripts -exec sudo sed -i 's/a/b/' {} \\;",
    "find scripts -exec ./tool {} \\;",
    "printf x>scripts/a.py",
    "echo x>>scripts/a.py",
    'echo x > "$PWD/scripts/a.py"',
    'OUT=scripts; echo x > "$OUT/a.py"',
    'cp /tmp/a "$UNSET_GUARD_VAR/a.py"',
    'HOME=$(id -un); echo x > "$HOME/scripts/a.py"',
    'A=/tmp; A=$OTHER_UNSET; echo x > "$A/f"',
    "cp -t scripts /tmp/a.py",
    "cp --target-directory=scripts /tmp/a.py /tmp/b.py",
    "install -t scripts /tmp/a",
    "mv --target-directory=/tmp scripts/a.py",
    "cd scripts && echo x > ../CLAUDE.md",
    "cd /tmp && cd - && echo x > a.py",
    "(cd /tmp && echo x > a) && echo y > b.py",
    "pushd /tmp && popd && echo y > b.py",
    'cd "$UNSET_DIR_VAR" && echo x > a.py',
    'OUT=scripts; echo x > "$OUT/a.py"; OUT=/tmp',
    'export OUT=scripts; echo x > "$OUT/a.py"',
    "rsync -t /tmp/a.py scripts/b.py",
    "cp -avt scripts /tmp/a.py",
    "install -pt scripts /tmp/a",
    "ln -st scripts /tmp/a",
    "cp -t./scripts /tmp/a.py",
    'A=scripts; (A=/tmp); echo x > "$A/x.py"',
    'A=/tmp; (A=scripts; echo x > "$A/y")',
    "chown --reference=/tmp/x scripts/a.py",
    'W=$(mktemp -d tmp.XXXXXX); echo x > "$W/a"',
    'W=$(mktemp -d scripts/tmp.XXXXXX); echo x > "$W/a"',
    'W=$(mktemp -d -p scripts x.XXXX); echo x > "$W/a"',
    "$(echo $(echo git) stash)",
    "$(echo $(echo rm) -f scripts/a.py)",
    "$(printf 'git reset --hard')",
    "osascript -e 'do shell script \"git reset --hard\"'",
    "bash<script.sh",
    "sh -s<script.sh",
    "bash<<<'git reset --hard'",
    "bash <<< \"$CMD\"",
    "cat script.sh | bash<<<'git reset --hard'",
    "uv run git reset --hard",
    "uv run rm scripts/x.py",
    "git branch -v scratch",
    "git tag --format='%(refname)' v1",
    'cd scripts && echo x > "$PWD/a.py"',
    "git --attr-source foo.attrs reset --hard",
    "git --super-prefix foo reset --hard",
    "git -X foo reset --hard",
    "git --unknown-opt value branch -D tmp",
    "git --attr-source log reset --hard",
    "git --attr-source status branch -D tmp",
    "git --unknown-opt log tag -d v1",
    "git --no-pager reset --hard",
    "git --unknown-opt log diff --output=patch.diff",
    "git -c alias.pwn='!git checkout -- f' pwn",
    "git -c alias.pwn='reset --hard' pwn",
    "git -c alias.pwn='!echo x > scripts/a.py' pwn",
    'git -c "alias.pwn=$BODY" pwn',
    # settings and variables git runs as a command
    "git -c diff.external='sh -c \"echo x > scripts/pwn.py\"' diff",
    "git -c core.fsmonitor='rm scripts/a.py' status",
    "git -c core.pager='tee scripts/a.py' log -1",
    "git -c filter.x.clean='rm scripts/a.py' show HEAD:a",
    "git -c pager.log='tee scripts/a.py' log -1",
    'git -c "diff.external=$X" diff',
    "git -c include.path=/tmp/evil.gitconfig log -1",
    "git --config-env=diff.external=EVIL diff",
    "git --config-env diff.external=EVIL diff",
    "GIT_EXTERNAL_DIFF='sh -c \"echo x > scripts/pwn.py\"' git diff",
    "GIT_PAGER='tee scripts/a.py' git log -1",
    "PAGER='tee scripts/a.py' git log -1",
    "export GIT_PAGER='tee scripts/a.py'; git log -1",
    "GIT_PAGER='tee scripts/a.py'\ngit log -1",
    'GIT_CONFIG_PARAMETERS="\'diff.external=rm scripts/a.py\'" git diff',
    "GIT_CONFIG_GLOBAL=/tmp/evil.gitconfig git log -1",
    'GIT_EXTERNAL_DIFF="$EVIL" git diff',
    "env GIT_CONFIG_GLOBAL=/tmp/evil.gitconfig git diff",
    "env GIT_PAGER='tee scripts/a.py' git log -1",
    "env -i GIT_EXTERNAL_DIFF='rm scripts/a.py' git diff",
    "command env GIT_PAGER='tee scripts/a.py' git log -1",
    # a repository script's subcommand the guard does not know as read-only
    "python3 scripts/autoevo_run.py rollback x",
    "python3 scripts/autoevo_commit.py audit x",
    "python3 scripts/shadow.py group-start --task x",
    "uv run scripts/autoevo_run.py plan",
    "uv run scripts/deadlines.py done x",
    "python3 scripts/autoevo_run.py Rollback",
    "python3 scripts/autoevo_run.py doRollback",
    "python3 scripts/autoevo_run.py 123abc",
    "python3 scripts/foo.py HEAD",
    "python3 scripts/autoevo_run.py list --Apply",
    "python3 scripts/autoevo_run.py list --APPLY",
    "uv run scripts/deadlines.py due --Force",
    "python3 scripts/foo.py --verbose rollback",
    "python3 scripts/foo.py --apply=1",
    "python3 scripts/foo.py --Force=true",
    "python3 scripts/foo.py --push=origin",
    "python3 scripts/foo.py --write=/tmp/x",
    "uv run scripts/deadlines.py --force=1 due",
    "python3 scripts/foo.py --fix-all=yes list",
    # an editor pointed at a repository file writes it
    "ed -s scripts/x.py",
    "ed -s scripts/x.py <<EOF\n,d\nw\nEOF",
    "vim -Nu NONE -n -es scripts/x.py",
    "ex -s scripts/x.py",
    "vi scripts/x.py",
    "nano scripts/x.py",
    "emacs --batch scripts/x.py",
    "vim -es",
    "vim -es +'w scripts/x.py'",
    "sudo vim scripts/x.py",
    "vim -c 'w scripts/x.py' -es /tmp/other.txt",
    "vim +'w scripts/x.py' -es",
    "vim -es -c '!rm scripts/x.py' /tmp/x",
    "vim -S /tmp/evil.vim /tmp/x",
    "vim -s /tmp/keys.txt /tmp/x",
    "emacs --batch --eval '(delete-file \"scripts/x.py\")'",
    "emacs -Q --batch -l /tmp/evil.el",
    "nano -s 'rm scripts/x.py' /tmp/x",
    "vim -c 'set nowrap | w scripts/x.py' -es /tmp/x",
    "emacs -l/tmp/badfile /tmp/x",
    "emacs --batch -l/tmp/evil.el",
    "nano -s/tmp/speller /tmp/x",
    "vim -S/tmp/evil.vim /tmp/x",
    "vim -es -S/tmp/evil.vim /tmp/x",
    "vim -s/tmp/keys.txt scripts/real_target.py /tmp/other",
    "nano -Afoobar /tmp/target scripts/x.py",
    "vim -Nes scripts/x.py",
    # formatters and fixers rewrite what they are pointed at
    "ruff check --fix scripts",
    "ruff check scripts --fix",
    "ruff format",
    "ruff format scripts",
    "black scripts",
    "black scripts/x.py",
    "isort scripts",
    "rustfmt scripts/x.rs",
    "prettier --write scripts/x.js",
    "eslint --fix scripts/x.js",
    "gofmt -w scripts/x.go",
    "shfmt -w scripts/x.sh",
    "yapf -i scripts/x.py",
    "autopep8 -i scripts/x.py",
    "clang-format -i scripts/x.c",
    "python3 -m black scripts",
    "python3 -m ruff check --fix scripts",
    "python -m isort scripts",
    "uvx black scripts",
    "uv run black scripts",
    "uvx ruff check --fix scripts",
    "npx prettier --write scripts/x.js",
    "biome format --write scripts/x.js",
    "biome lint --apply scripts/x.js",
    "uvx ruff format scripts",
    "uv run ruff check --fix scripts",
    "uv run --with ruff ruff format scripts",
    "sed -i -e 's/a/b/' scripts/x.py",
    "perl -i -e 's/a/b/' scripts/x.py",
    "sed -i --expression='s/a/b/' scripts/x.py",
    "perl -i -Es/a/b/ scripts/x.py",
    "perl -pi -Es/a/b/ scripts/x.py",
    "perl -i -E 's/a/b/' scripts/x.py",
    "perl -pi -e's/a/b/' scripts/x.py",
    # a repository script's output flag names where it writes
    "python3 scripts/daily_context.py --json --offline --out scripts/probe.json",
    "uv run scripts/foo.py --output=scripts/x.json",
    "python3 scripts/foo.py -o scripts/x.json",
    "./scripts/foo.py --out-dir scripts",
    "python3 scripts/foo.py list --dest scripts/out",
    'python3 scripts/foo.py --out "$TMP/x"',
    "python3 scripts/foo.py --out -write.json",
    "python3 scripts/foo.py -vo scripts/x.json",
    "python3 scripts/foo.py -vo=scripts/x.json",
    "python3 scripts/foo.py -voscripts/x.json",
    "python3 scripts/foo.py -oscripts/x.json",
    # a git argument the command assembled
    'ARGS=--output=scripts/p.patch; git diff "$ARGS"',
    'git diff "$ARGS"',
    "git log $REV",
    'git log -- "$f"',
    'OUT=scripts/p.patch; git diff --output "$OUT"',
    'echo "$(git reset --hard)"',
    'echo "it\'s $(git reset --hard)"',
    "echo `git reset --hard`",
    "python3 -c \"import subprocess; subprocess.run(['git', 'log', n])\"",
    # every interpreter on the line is read, not only the first
    "python3 -c 'print(1)'; python3 -c \"open('scripts/a.py', 'w').write('x')\"",
    "python3 -c 'print(1)' && node -e \"require('fs').rmSync('scripts/x.js')\"",
    "echo | python3 -c 'print(1)' | python3 -c \"import os; os.remove('scripts/a.py')\"",
    "python3 -c 'print(1)'; python3 /tmp/mutate.py",
    "python3 -c \"print('$HOME')\"",
    "python3 -c \"from pathlib import Path; p = Path('scripts') / 'x.py'; p.write_text('x')\"",
    "python3 -c \"import os; os.execv('/bin/sh', ['sh', '-c', 'git reset --hard'])\"",
    "python3 -c \"import os; base = 'scripts'; p = os.path.join(base, 'x.py'); os.remove(p)\"",
    "sed --in-place=.bak 's/a/b/' scripts/x.py",
    "sed --in-place=.bak -e 's/a/b/' scripts/x.py",
    "python3 -c \"import os; os.open('scripts/x.py', os.O_CREAT | os.O_WRONLY)\"",
    "python3 -c \"import os; os.open('scripts/x.py', os.O_RDWR)\"",
    "python3 -c \"import os; os.open('scripts/x.py', flags)\"",
    # ruby and perl write without parentheses
    "ruby -e \"File.write 'scripts/x.rb', 'x'\"",
    "perl -e 'unlink \"scripts/x.pl\"'",
    "perl -e 'rename \"a\", \"scripts/x.pl\"'",
    "perl -e 'mkdir \"scripts/new\"'",
    "perl -e 'open(FH, \">scripts/x.pl\")'",
    "perl -e 'open(FH, \">>scripts/x.pl\")'",
    "ruby -e \"FileUtils.rm_rf('scripts')\"",
    "ruby -e \"FileUtils.mv 'a', 'scripts/x.rb'\"",
    "ruby -e \"FileUtils.touch 'scripts/x.rb'\"",
    "ruby -e \"FileUtils.cp_r '/tmp/a', 'scripts/a'\"",
    "perl -e 'open FH, \">scripts/x.pl\"; print FH 1'",
    "perl -e 'open FH, \">>scripts/x.pl\"'",
    "python3 -c \"from pathlib import Path; Path('scripts/x.py').replace('/tmp/y')\"",
    # an unquoted heredoc is expanded by the shell before anything reads it
    "cat <<EOF\n$(git reset --hard)\nEOF",
    "cat <<EOF\n`git reset --hard`\nEOF",
    "cat <<-EOF\n$(git reset --hard)\nEOF",
    "cat <<EOF > /tmp/x\n$(rm scripts/a.py)\nEOF",
    "cat <<EOF\n$(echo $(git reset --hard))\nEOF",
    "cat <<EOF\ntext $(rm scripts/a.py) text\nEOF",
    # a later rebinding does not rewrite an earlier use
    "python3 -c \"from pathlib import Path; p = Path('scripts/x.py'); p.unlink(); p = Path('/tmp/decoy')\"",
    "python3 -c \"from pathlib import Path; p = Path('scripts/x.py'); p.write_text('a'); p = Path('/tmp/s'); p.write_text('b')\"",
    "python3 -c \"f = open('scripts/x.py', 'w'); f.write('x'); f = open('/tmp/x', 'w')\"",
    "python3 -c \"from pathlib import Path; p = Path('/tmp/x'); p = Path('scripts/x.py'); p.unlink()\"",
    "python3 -c \"from pathlib import Path; p = Path('/tmp/x'); p = compute(); p.unlink()\"",
    # a rebinding inside a nested block may or may not run
    'python3 -c "from pathlib import Path\np = Path(\'scripts/x.py\')\nif False:\n    p = Path(\'/tmp/decoy\')\np.unlink()"',
    'python3 -c "from pathlib import Path\np = Path(\'scripts/x.py\')\ndef f():\n    p = Path(\'/tmp/decoy\')\np.unlink()"',
    'python3 -c "from pathlib import Path\nif cond:\n    p = Path(\'scripts/x.py\')\np.unlink()"',
    'python3 -c "from pathlib import Path\np = Path(\'/tmp/x\')\ntry:\n    p = Path(\'scripts/x.py\')\nexcept Exception:\n    pass\np.unlink()"',
    # sibling branches at equal indentation
    'python3 -c "from pathlib import Path\nif cond:\n    p = Path(\'scripts/x.py\')\nelse:\n    p = Path(\'/tmp/decoy\')\np.unlink()"',
    'python3 -c "from pathlib import Path\ntry:\n    p = Path(\'scripts/x.py\')\nexcept Exception:\n    p = Path(\'/tmp/decoy\')\np.unlink()"',
    'python3 -c "from pathlib import Path\nif a:\n    p = Path(\'scripts/x.py\')\nelif b:\n    p = Path(\'/tmp/y\')\nelse:\n    p = Path(\'/tmp/decoy\')\np.unlink()"',
    'python3 -c "from pathlib import Path\np = Path(\'scripts/x.py\')\nfor x in y:\n    p = Path(\'/tmp/decoy\')\np.unlink()"',
    "python3 scripts/foo.py --verbose Done x",
    "python3 scripts/foo.py apply.now",
    "python3 scripts/foo.py rm.all",
    # input redirections do not hide the verb or the program
    "git < /tmp/in reset --hard",
    "git --no-pager < /tmp/in branch -D tmp",
    "git </tmp/in reset --hard",
    "git 0< /tmp/in reset --hard",
    "git <&3 reset --hard",
    "git 0<> /tmp/in reset --hard",
    "git <<< data reset --hard",
    "git <<EOF reset --hard",
    "git << EOF reset --hard",
    "git log 0<> scripts/a.py",
    "python3 < /tmp/mutate.py",
    "python3 </tmp/mutate.py",
    "python3 0< /tmp/mutate.py",
    "node < /tmp/mutate.js",
    "python3 - < /tmp/mutate.py",
    "python3 <<< 'open(\"scripts/a.py\", \"w\").write(\"x\")'",
    'python3 <<< "$PAYLOAD"',
    "python3 - <<EOF < /tmp/mutate.py\nprint(1)\nEOF",
    "sh <<< 'git reset --hard'",
    'bash <<< "$PAYLOAD"',
    "sh <<EOF < /tmp/x.sh\necho hi\nEOF",
    "echo x2>scripts/a.py",
    "git > /tmp/o reset --hard",
    "git 2>/dev/null reset --hard",
    "git 2>&1 reset --hard",
    "git &>/dev/null reset --hard",
    "git --no-pager 2>/dev/null branch -D tmp",
    "python3 >/tmp/o /tmp/mutate.py",
    "python3 2>/dev/null /tmp/mutate.py",
    "node 2>&1 /tmp/mutate.js",
    "perl 2>/dev/null -i.bak -pe s/a/b/ scripts/a.py",
    "git log >&scripts/a.py",
    # a literal nested in the argument expression is spelled out
    "python3 -c \"import os; from pathlib import Path; os.remove(Path('scripts/x.py'))\"",
    "python3 -c \"import shutil; from pathlib import Path; shutil.copy('/tmp/a', Path('scripts/x.py'))\"",
    "python3 -c \"import os; os.remove(str(Path('scripts/x.py')))\"",
    "python3 -c \"import os; os.remove(os.path.join('scripts', 'x.py'))\"",
    "python3 -c \"import os; os.remove(Path('scripts') / 'x.py')\"",
    "python3 -c \"open(Path('scripts/x.py'), 'w')\"",
    "python3 -c \"from pathlib import Path; p = Path('scripts'); import os; os.remove(p / 'x.py')\"",
    "python3 -c \"import shutil; shutil.move('/tmp/a', dst=Path('scripts/x.py'))\"",
    # an unreadable source does not pull the destination into its slot
    "python3 -c \"import shutil; shutil.copy(src, 'scripts/x.py')\"",
    "python3 -c \"import shutil; shutil.copy(sys.argv[1], 'scripts/x.py')\"",
    "python3 -c \"import os; os.rename(a, 'scripts/x.py')\"",
    # a shell-out or write not fully spelled out is unscannable
    "python3 -c \"cmd='reset'; subprocess.run(['git', cmd, '--hard'])\"",
    "python3 -c \"import subprocess; subprocess.run(['git', sys.argv[1]])\"",
    "python3 -c \"import subprocess; subprocess.run(cmd)\"",
    "python3 -c \"import subprocess; subprocess.run('git ' + verb, shell=True)\"",
    "python3 -c \"import subprocess; subprocess.run(f'git {verb}', shell=True)\"",
    "python3 -c \"import subprocess; subprocess.run('{} reset --hard'.format('git'), shell=True)\"",
    "python3 -c \"import subprocess; subprocess.run('%s reset --hard' % tool, shell=True)\"",
    "python3 -c \"import subprocess; subprocess.run(['rm', path])\"",
    "python3 -c \"import subprocess; subprocess.run(['git'] + args)\"",
    "python3 -c \"open(name, 'w')\"",
    "python3 -c \"import shutil; shutil.copy('scripts/x.py', dest)\"",
    "python3 -c \"import os; os.remove(sys.argv[1])\"",
    "ruby -e \"system('git', cmd)\"",
    "node -e \"require('child_process').execSync(cmd)\"",
    "python3 -c \"import subprocess as sp; sp.run(['git', cmd])\"",
    "python3 -c \"from subprocess import run; run(['git', cmd])\"",
    "python3 -c \"from subprocess import *; run(['git', cmd])\"",
    "python3 -c \"import subprocess as sp; sp.run('git reset --hard', shell=True)\"",
    "python3 -c \"open(f'{d}/x.py', 'w')\"",
    "python3 -c \"open('{}/x.py'.format(d), 'w')\"",
    "python3 -c \"open('%s/x.py' % d, 'w')\"",
    # a quoted program that spans lines is read whole
    'python3 -c "import os\nos.remove(\'scripts/x.py\')"',
    "python3 -c 'import subprocess\nsubprocess.run([\"git\", \"reset\", \"--hard\"])'",
    'python3 -c "import subprocess\ndef run(c): subprocess.run(c, shell=True)\nrun(\'git reset --hard\')"',
    'sh -c "echo hi\ngit reset --hard"',
    # a heredoc operator glued to the command word
    "bash<<EOF\ngit reset --hard\nEOF",
    "sh<<'EOF'\nrm scripts/a.py\nEOF",
    'python3<<EOF\nopen("scripts/a.py", "w")\nEOF',
    "bash<<-EOF\n\tgit reset --hard\nEOF",
    "node -e \"require('child_process').spawn('git', [verb])\"",
    # Node's fs verbs
    "node -e \"require('fs').unlinkSync('scripts/x.js')\"",
    "node -e \"fs.renameSync('/tmp/a', 'scripts/x.js')\"",
    "node -e \"fs.renameSync('scripts/x.js', '/tmp/b')\"",
    "node -e \"fs.rmSync('scripts/x.js', {force: true})\"",
    "node -e \"fs.mkdirSync('scripts/new')\"",
    "node -e \"fs.copyFileSync('/tmp/a', 'scripts/x.js')\"",
    "node -e \"fs.cpSync('/tmp/a', 'scripts/x.js')\"",
    "node -e \"fs.openSync('scripts/x.js', 'w')\"",
    "node -e \"fs.truncateSync('scripts/x.js')\"",
    "node -e \"fs.promises.rm('scripts/x.js')\"",
    "node -e \"const {rmSync} = require('fs'); rmSync('scripts/x.js')\"",
    "node -e \"fs.rmSync(p)\"",
    "node -e \"const {rm} = require('fs'); rm('scripts/x.js')\"",
    "node -e \"const fsPromises = require('fs').promises; fsPromises.rm('scripts/x.js')\"",
    "node -e \"const {cp} = require('fs/promises'); cp('/tmp/a', 'scripts/x.js')\"",
    "node -e \"const {rmSync} = require('node:fs'); rmSync('scripts/x.js')\"",
    "python3 -c \"from subprocess import run as r; r(['git', 'reset', '--hard'])\"",
    "python3 -c \"from subprocess import Popen as P; P(['git', 'reset', '--hard'])\"",
    "python3 -c \"from subprocess import (run as r, PIPE); r(['git', cmd])\"",
    # names bound to a shell-out or a write API are followed
    "python3 - <<'EOF'\nfrom subprocess import (\n    run as r,\n    call,\n)\nr(['git', 'reset', '--hard'])\nEOF",
    "node -e \"const {rm: removeIt} = require('fs'); removeIt('scripts/x.js')\"",
    "node -e \"import { rm as removeIt } from 'fs/promises'; removeIt('scripts/x.js')\"",
    "node -e \"const removeIt = fs.rmSync; removeIt('scripts/x.js')\"",
    "node -e \"const removeIt = require('fs').rmSync; removeIt('scripts/x.js')\"",
    "python3 -c \"from os import remove as delete_file; delete_file('scripts/x.py')\"",
    "python3 -c \"from shutil import copy as cp; cp('/tmp/a', 'scripts/x.py')\"",
    "python3 -c \"import os; f = os.remove; f('scripts/x.py')\"",
    "python3 -c \"f = open; f('scripts/x.py', 'w')\"",
    "python3 -c \"import subprocess; r = subprocess.run; r(['git', 'reset', '--hard'])\"",
    "python3 -c \"import subprocess as sp; r = sp.run; r(['git', cmd])\"",
    # a mutating method on a receiver the guard cannot read
    "python3 -c \"p.rename('/tmp/out')\"",
    "python3 -c \"from pathlib import Path; p = Path('scripts/x.py'); p.rename('/tmp/out')\"",
    "python3 -c \"from pathlib import Path; Path(p).write_text('x')\"",
    "python3 -c \"from pathlib import Path; p = 'scripts/x.py'; Path(p).write_text('x')\"",
    "python3 -c \"f.write('x')\"",
    "python3 -c \"with open('scripts/x.py', 'w') as f: f.write('x')\"",
    "python3 -c \"f = open('scripts/x.py', 'w'); f.write('x')\"",
    "python3 -c \"import tempfile; d = tempfile.mkdtemp(); open('scripts/x.py', 'w')\"",
    # a chain of bindings
    'python3 -c "from subprocess import run as r\ng = r\ng([\'git\', \'reset\', \'--hard\'])"',
    'python3 -c "import subprocess\nsp = subprocess\nsp.run([\'git\', \'reset\', \'--hard\'])"',
    'python3 -c "import subprocess\nsp = subprocess\nsp.run([\'git\', cmd])"',
    'python3 -c "import os\nd = os.remove\ne = d\ne(\'scripts/x.py\')"',
    "node -e \"const {rm} = require('fs'); const removeIt = rm; removeIt('scripts/x.js')\"",
    "node -e \"const {execSync: e} = require('child_process'); e('git reset --hard')\"",
    "python3 -c \"import os; s = os.system; s('git reset --hard')\"",
    "python3 -c \"from os import system as s; s('git reset --hard')\"",
    "python3 -c \"from os import popen as p; p('git reset --hard')\"",
    # quoted program text survives the wrapper's rescan; inline code only
    "bash -c 'python3 -c \"open(\\\"scripts/a.py\\\",\\\"w\\\")\"'",
    "sh -c 'python3 -c \"import os; os.remove(\\\"scripts/a.py\\\")\"'",
    'python3 -c "$CODE"',
    "node -p \"require('fs').rmSync('scripts/x.js')\"",
    "node --eval \"require('fs').rmSync('scripts/x.js')\"",
    "node --eval=\"require('fs').rmSync('scripts/x.js')\"",
    "node -r /tmp/evil.js scripts/x.js",
    "perl -E \"unlink('scripts/a.py')\"",
    "perl -ne \"unlink('scripts/a.py')\" README.md",
    "python3 -c\"open('scripts/a.py', 'w')\"",
    # a definition a later binding shadows is not the program's own
    'python3 -c "def remove(item):\n    return item\nfrom os import remove\nremove(\'scripts/x.py\')"',
    "node -e \"function unlink(a) { return a } const {unlink} = require('fs'); unlink('scripts/x.js')\"",
    "node -e \"function cp(a, b) { return a } const {cp} = require('fs'); const other = cp; other('/tmp/a', 'scripts/x.js')\"",
    "a=1>scripts/a.py",
    "perl -e 'my $x = `git reset --hard`'",
    "python3 -c \"open('scripts/x.py', 'w').write('x')\"",
    "python3 -c \"from pathlib import Path; Path('scripts/x.py').write_text('x')\"",
    "python3 - <<'EOF'\nimport shutil\nshutil.copy('/tmp/a.py', 'scripts/a.py')\nEOF",
    "python3 -c \"import os; os.remove('scripts/x.py')\"",
    "node -e \"require('fs').writeFileSync('scripts/x.js', 'x')\"",
    "php -r \"file_put_contents('scripts/x.php', 'x');\"",
    "python3 -c \"open('scripts/x.py','w').write('x')\"",
    "python3 -c \"subprocess.run(['git','reset','--hard'])\"",
    "python3 -c\"os.system('git reset --hard')\"",
    "python3 -c\"open('scripts/x.py','w').write('x')\"",
    "ruby -e\"File.write('scripts/x.rb','x')\"",
    "perl -e\"system('git reset --hard')\"",
    "python3 -c \"from pathlib import Path; p = Path('scripts/x.py'); p.unlink()\"",
    "python3 -c \"import os; target = 'scripts/x.py'; os.remove(target)\"",
    'X=scripts; X=/tmp echo x > "$X/a.txt"',
    "python3.13 scripts/harness_lint.py --fix-used-by",
    "python3 -mscripts.recurring done x",
    "python3.12 -c \"open('scripts/x.py','w').write('x')\"",
    "perl5.30 -e 'system(\"git reset --hard\")'",
    "node20 -e \"require('fs').writeFileSync('scripts/x.js', 'x')\"",
    "pypy3 /tmp/x.py",
    "python3 -c \"open(file='scripts/x.py', mode='w').write('x')\"",
    "python3 -c \"import shutil; shutil.copy(src='/tmp/a', dst='scripts/a.py')\"",
    "python3 -c \"import os; os.rename(src='/tmp/a', dst='scripts/a.py')\"",
    "python3 -c \"import shutil; shutil.move('/tmp/a', dst='scripts/a.py')\"",
    "python3 -c 'title = \"hi \\\" there\"; open(\"scripts/x.py\", \"w\").write(\"x\"); y = \"done\"'",
    "python3 -c \"import os; os.remove('scripts/x.py'); open('README.md', 'r').read()\"",
    "python3 -c \"from pathlib import Path; open('README.md').read(); Path('scripts/x.py').write_text('x')\"",
    "python3 -c \"open('scripts/x.py', mode='w').write('x')\"",
    "python3 -c \"open('README.md').read(); open('scripts/x.py', 'a').write('x')\"",
    "python3 -c \"open('scripts/x.py', 'rb+').write(b'x')\"",
    "python3 -c \"open('scripts/x.py', 'bw').write(b'x')\"",
    "python3 -c \"open('scripts/x.py', 'ba').write(b'x')\"",
    "python3 -c \"open('scripts/x.py', 'rt+').write('x')\"",
    "python3 -c \"import subprocess; subprocess.run(['rm', 'scripts/x.py'])\"",
    "python3 -c \"import subprocess; subprocess.run('rm scripts/x.py', shell=True)\"",
    "python3 -c \"import subprocess; subprocess.run('echo x > scripts/x.py', shell=True)\"",
    "tar -cf scripts/out.tar README.md",
    "tar --create --file=scripts/out.tar README.md",
    "tar -xf /tmp/a.tar",
    "tar -xf /tmp/a.tar -C scripts",
    "tar --extract --file=/tmp/a.tar --directory=scripts",
    "zip scripts/out.zip README.md",
    "unzip /tmp/a.zip",
    "unzip /tmp/a.zip -d scripts",
    "gzip README.md",
    "gzip -k README.md",
    "xz scripts/big.log",
    "tar --remove-files -cf /tmp/out.tar scripts/x.py",
    "zip -m /tmp/out.zip scripts/x.py",
    "rsync --remove-source-files scripts/a.py /tmp/a.py",
    "git worktree add /tmp/wt",
    "git worktree remove /tmp/wt",
    "python3 - <<'EOF'\nimport subprocess\nsubprocess.run([\n    'rm',\n    'scripts/x.py',\n])\nEOF",
    "python3 - <<'EOF'\nopen(\n    'scripts/x.py',\n    'w',\n).write('x')\nEOF",
    "python3 /tmp/x.py",
    "node /tmp/x.js",
    "echo 'import os' | python3 -",
    "cat /tmp/x.py | python3",
    "python3",
    "tar cf scripts/out.tar README.md",
    "tar xf /tmp/a.tar",
    "tar zcf scripts/out.tgz README.md",
    "curl -o scripts/x.py https://example.com/x.py",
    "curl -O https://example.com/x.py",
    "wget -O scripts/x.py https://example.com/x.py",
    "wget https://example.com/x.py",
    "wget -P scripts https://example.com/x.py",
    "curl -Lo scripts/x.py https://example.com/x.py",
    "curl -oscripts/x.py https://example.com/x.py",
    "curl -sLO https://example.com/x.py",
    "wget -qO scripts/x.py https://example.com/x.py",
    "wget -Oscripts/x.py https://example.com/x.py",
    "wget -Pscripts https://example.com/x.py",
    ": <> scripts/x.py",
    ":<>scripts/x.py",
    "exec 3<> scripts/x.py",
    "gawk -i inplace -e '{gsub(/a/,\"b\")}' scripts/x.py",
    "awk -i inplace '{print}' scripts/x.py",
    "gawk --include=inplace '{print}' scripts/x.py",
    "awk 'BEGIN{system(\"git reset --hard\")}'",
    "awk 'BEGIN{print \"x\" > \"scripts/pwned.py\"}'",
    "awk '{print | \"sh\"}' /tmp/x",
    "awk 'BEGIN{system(cmd)}'",
    "sed '1e git reset --hard' /tmp/x.txt",
    "sed 's/.*/git reset --hard/e' /tmp/x.txt",
    "sed -n 'w scripts/x.py' /tmp/x.txt",
    "sed 's/a/b/w scripts/x.py' /tmp/x.txt",
    "sed -f /tmp/prog.sed README.md",
    "awk -f /tmp/prog.awk README.md",
    "awk 'BEGIN{system(\"git \" \"reset --hard\")}'",
    "awk 'BEGIN{print \"x\" > \"sc\" \"ripts/pwned.py\"}'",
    "awk 'BEGIN{print \"x\" > out}'",
    "awk 'BEGIN{cmd=\"git\"; system(cmd \" reset --hard\")}'",
    "awk '{print | \"s\" \"h\"}' /tmp/x",
    "xargs python3 -c \"open('scripts/x.py','w').write('x')\"",
    "find . -name '*.py' -exec python3 -c \"open('scripts/x.py','w').write('x')\" \\;",
    "python3 -c \"from pathlib import Path; Path('scripts/x.py').open(mode='w').write('x')\"",
    "python3 -c \"from pathlib import Path; Path('scripts/x.py').open('w').write('x')\"",
    "python3 scripts/render_runtime_edges.py --runtime codex --apply",
    "python3 scripts/harness_lint.py --fix-used-by",
    "python3 scripts/recurring.py done mattresses-rotate",
    "python3 scripts/privacy_index.py build --force",
    "uv run scripts/recurring.py done mattresses-rotate",
    "uv run scripts/privacy_index.py build --force",
    "uv run scripts/harness_lint.py --fix-used-by",
    "python3 -m scripts.recurring done x",
    "./scripts/recurring.py done x",
    "uv run --directory /repo scripts/recurring.py done x",
    "uv run --python 3.11 scripts/recurring.py done x",
    "uv tool run scripts/recurring.py done x",
    "true; ./scripts/recurring.py done x",
    "echo start && ./scripts/recurring.py done x",
    "uvx ruff check --fix scripts",
    "uvx ruff format scripts",
    "uv run /tmp/x.py",
    "git diff > patch.diff",
    "git show HEAD:scripts/x.py > scripts/x.py",
    "git log -1 >> notes.md",
    "git --no-pager diff > patch.diff",
    "codex exec 'git reset --hard'",
    "claude -p 'edit scripts/x.py'",
    "git hash-object -w scripts/x.py",
    "python3 -c \"open('scratch', 'w').write('x')\"",
    "python3 -c \"import shutil; shutil.copy('/tmp/a.py', 'scratch')\"",
    "python3 -c \"import os; os.rename('scripts/x.py', '/tmp/x.py')\"",
    "python3 -c \"from pathlib import Path; Path('scratch').write_text('x')\"",
    "python3 -c \"import os; os.unlink('scripts/x.py')\"",
    "python3 -c \"import os; os.rmdir('scripts/subdir')\"",
    "python3 -c \"import os; os.mkdir('scripts/newdir')\"",
    "python3 -c \"import os; os.truncate('scripts/x.py', 0)\"",
    "python3 -c \"import os; os.chmod('scripts/x.py', 0o755)\"",
    "python3 -c \"import os; os.rename('/tmp/a.py', 'scripts/dest.py')\"",
    "python3 -c \"import os; os.symlink('/tmp/a.py', 'scripts/dest_link')\"",
    "python3 -c \"import os; os.link('/tmp/a.py', 'scripts/dest_hardlink')\"",
    "python3 - <<'EOF'\nfrom pathlib import Path\np = Path('scripts/x.py')\np.unlink()\nEOF",
    "python3 - <<'EOF'\nfrom pathlib import Path\np = Path('scripts/x.py')\np.write_text('/tmp/not-a-target')\nEOF",
    "python3 - <<'EOF'\n(\n    Path('scripts/x.py')\n    .write_text('/tmp/not-a-target')\n)\nEOF",
    "python3 - <<'EOF'\ntarget = 'scripts/x.py'\nopen(target, 'w').write('x')\nEOF",
    "echo x&>scripts/a.py",
    "echo x&>>scripts/a.py",
    "python3 -c \"import subprocess; subprocess.run(('rm', 'scripts/x.py'))\"",
    "python3 -c \"import subprocess; subprocess.run(('cp', '/tmp/a', 'scripts/x.py'))\"",
)
ALLOWED = (
    "git show HEAD:scripts/a.py",
    "git show abc123:scripts/a.py | head -n 20",
    "git diff",
    "git diff main..HEAD --stat",
    "git log -1 --format=%H -- scripts/a.py",
    "git status --short",
    "git -C /tmp/v rev-parse --show-toplevel",
    "python3 -m unittest tests.test_reviewer_contract",
    "grep -n stash scripts/a.py",
    "cat <<'EOF'\nnever stash, checkout, restore, apply, reset, or edit\nEOF",
    "python3 - <<'EOF'\nsubprocess.run(['git', 'show', 'HEAD:a.py'])\nEOF",
    "bash -lc 'git show HEAD:a.py | head'",
    "sh -c 'git log -1 --format=%H'",
    'rg -n "git reset" scripts',
    'grep -R "git checkout -- file" .',
    "git log --grep 'git stash' -n 5",
    "git branch",
    "git branch -a",
    "git branch --contains abc123",
    "git branch --show-current",
    "git tag -l 'v*'",
    "git tag --contains abc123",
    "git reflog",
    "git reflog show HEAD",
    "git remote -v",
    "git config --get user.name",
    "rg git reset scripts",
    'rg -n "(git|reset)" scripts',
    "git log --format='%H (%s)' -n 3",
    "awk '{print $1}' names.txt",
    "bash -c 'git show HEAD:a.py' -- a.py",
    "python3 - <<'EOF'\nimport subprocess\nprint(subprocess.run(['git', 'show', 'HEAD:a.py']))\nEOF",
    "uv run python - <<'EOF'\nimport json\nprint(json.dumps({'git': 'show'}))\nEOF",
    "git ls-files | xargs grep -n stash",
    "find . -name '*.md' | xargs cat",
    "cd \"$OV\" && git log -1",
    "git -C \"$OV\" log -1",
    'uv run "${CLAUDE_PROJECT_DIR:-.}/scripts/cues.py" --hook',
    "echo $HOME",
    "sudo -u root git log -1",
    "bash <<'EOF'\ngit show HEAD:a.py\nEOF",
    "git \\\nlog -1",
    "echo x > /tmp/probe.py",
    "cat > /tmp/probe.py <<'EOF'\nDENIED = (\"git stash\", 'git restore a.py')\ngit reset --hard\nEOF",
    "cp scripts/_git.py /tmp/backup.py",
    "sed -n '1,5p' scripts/_git.py",
    "sed -e 's/a/b/' scripts/_git.py | head",
    "git diff > /tmp/d.diff",
    "python3 -m unittest tests.test_git_retry 2>&1 | tail -n 3",
    "python3 x.py > /dev/null 2>&1",
    "W=$(mktemp -d); cp scripts/x.py \"$W/x.py\"",
    "tee /tmp/log.txt",
    "patch --dry-run -p1 < /tmp/fix.diff",
    "python3 - <<'EOF'\nDENIED = ('git reset --hard',)\nprint(DENIED)\nEOF",
    "git diff --output=/tmp/patch.diff",
    "git config user.name",
    "git symbolic-ref HEAD",
    "git symbolic-ref --short HEAD",
    "git lfs ls-files",
    "rg 'a|b' scripts",
    "echo 'x;y'",
    "git log --format='%h;%s' -n 3",
    "grep -c '&&' scripts/x.py",
    "git log -1&&git status",
    "rm -f /tmp/a.py 2>/dev/null",
    "rm -f /tmp/a.py > /dev/null 2>&1",
    "cp /tmp/a /tmp/b 2>/dev/null",
    "rm -rf /tmp/probe*.py 2>/dev/null; echo cleaned",
    "python3 -c 'print(\"run(git)\")'",
    "git branch --contains abc123 2>/dev/null",
    "find /tmp/probe -delete",
    "find /tmp/probe -exec rm {} \\;",
    "find scripts -name '*.py' -exec grep -l foo {} \\;",
    "chmod +x /tmp/probe.sh",
    "chown user /tmp/probe.sh",
    "git ls-files | xargs wc -l",
    "cat x.py | tee /tmp/copy.py >| /tmp/copy2.py",
    "chmod -w /tmp/probe.sh",
    "chmod 644 /tmp/probe.sh",
    "cp /tmp/a{,.bak}",
    "rg 'x{2}' scripts",
    "echo ${HOME}",
    "{ git log -1; git status; }",
    "chmod u+rwx,g+r /tmp/probe.sh",
    "cp {/tmp/a.py,/tmp/b.py}",
    "mv /tmp/a.py /tmp/b.py",
    "echo git reset --hard",
    "cat git reset",
    "caffeinate git log -1",
    "watch -n1 git status --short",
    "watch -n1 'git status --short'",
    "flock -c 'git log -1' /tmp/lock",
    'OUT=/tmp/out; echo x > "$OUT/a.txt"',
    'W=$(mktemp -d); echo x > "$W/a.txt"',
    'echo x > "${TMPDIR:-/tmp}/a.txt"',
    "find scripts -exec grep -l foo {} \\;",
    "echo 'a>b'",
    "sed --posix 's/a/b/' scripts/x.py",
    "sed --quiet 's/a/b/p' scripts/x.py",
    "cd /tmp && echo x > a.txt",
    "cd /tmp && cp -t . /tmp/a.py",
    "(cd /tmp && echo x > a)",
    "pushd /tmp && echo x > a && popd",
    "cd /tmp\necho x > b.txt",
    'OUT=/tmp; echo x > "$OUT/a.txt"; OUT=scripts',
    "echo x > ~/guard-probe.txt",
    "echo x > ~/nonexistent-guard-home/a.py",
    "cd ~ && echo x > guard-probe.txt",
    "rsync -t /tmp/a.py /tmp/b.py",
    "rsync -avz scripts/ /tmp/backup/",
    "cp -avt /tmp /tmp/a.py",
    'W=$(mktemp -d /tmp/tmp.XXXXXX); echo x > "$W/a"',
    'W=$(mktemp -d -t guard); echo x > "$W/a"',
    'W=$(mktemp -d -p /tmp x.XXXX); echo x > "$W/a"',
    'W=$(mktemp -d --tmpdir=/tmp x.XXXX); echo x > "$W/a"',
    'A=/tmp; (A=scripts); echo x > "$A/x.txt"',
    "echo $(echo $(echo hi))",
    "grep -c x <script.sh",
    "wc -l <<<'git reset --hard'",
    "osascript -e 'display notification \"done\"'",
    "uv run python -m unittest tests.test_git_retry",
    "uv run scripts/lint.py --json",
    "uvx ruff check scripts",
    "git branch -v",
    "git tag --format='%(refname)'",
    'cd /tmp && echo x > "$PWD/a.txt"',
    "git --no-pager log -1",
    "git --no-optional-locks status --short",
    "git log --grep stash -n 3",
    "git --no-pager log --grep stash -n 3",
    "git --attr-source HEAD status --short",
    "git --unknown-opt log diff --output=/tmp/patch.diff",
    "git -c alias.lg='log --oneline -5' lg",
    "git -c alias.st='!git status --short' st",
    "git -c core.pager=cat log -1",
    "git -c core.pager=cat < /tmp/in log -1",
    "git -c core.pager='less -R' log -1",
    "git -c diff.external='git diff --no-index' diff",
    "git -c color.ui=always diff",
    "git -c core.quotepath=off status --short",
    "PAGER=cat git log -1",
    "GIT_PAGER=cat git log --oneline -3",
    "GIT_CONFIG_GLOBAL=/dev/null git log -1",
    "GIT_CONFIG_NOSYSTEM=1 git log -1",
    "GIT_DIR=.git git log -1",
    "env -i PATH=/usr/bin git log -1",
    "env GIT_PAGER=cat git log -1",
    "uv run scripts/routine_audit.py health",
    "uv run scripts/privacy_index.py why term",
    "uv run scripts/routine_digest.py check",
    "uv run scripts/deadlines.py due",
    "python3 scripts/harness_lint.py",
    "uv run scripts/eval_run.py --no-semantic",
    "python3 scripts/foo.py --mode fast",
    "python3 scripts/foo.py -n 5 list",
    "python3 scripts/foo.py --runtime codex -- list",
    "python3 scripts/foo.py 2026-09-05",
    "python3 scripts/foo.py 3.14",
    "python3 scripts/foo.py notes/today.md",
    "python3 scripts/foo.py 'two words'",
    "python3 scripts/foo.py v1.2.3",
    "python3 scripts/foo.py wiki/Foo",
    "python3 scripts/foo.py README.md",
    "python3 scripts/foo.py ./local",
    "python3 scripts/foo.py ~/notes",
    # later words are data, whatever they spell
    "python3 scripts/foo.py list format",
    "python3 scripts/foo.py show update",
    "python3 scripts/recurring.py list rotate",
    "uv run scripts/deadlines.py due edit",
    "python3 scripts/foo.py List",
    "python3 scripts/foo.py --limit=5 list",
    "python3 scripts/foo.py --format=json list",
    "vim --version",
    "ed /tmp/x",
    "vim -es /tmp/notes.txt",
    "vim -c 'syntax on' -es /tmp/other.txt",
    "vim -c 'set nowrap' -es /tmp/scratch.txt",
    "vim -c 'set nowrap | syntax on' -es /tmp/x",
    "vim -es -c q /tmp/x",
    "vim -Nu NONE -n -es /tmp/x",
    "vim -u NONE /tmp/x",
    "emacs -Q --batch /tmp/x",
    "ed -p '*' /tmp/x",
    "nano -T 4 /tmp/x",
    "ed -p'*' /tmp/x",
    "vim -uNONE /tmp/x",
    "vim -Nes /tmp/x",
    "vim -nes /tmp/x",
    "vim -Nu NONE -i NONE -n -es /tmp/x",
    "ed - /tmp/x",
    "ruff check scripts",
    "uvx ruff check scripts tests --select F,E4,E7,E9,EXE001",
    "ruff format --check scripts",
    "ruff format --diff scripts",
    "black --check scripts",
    "black --diff scripts",
    "black /tmp/x.py",
    "isort --check-only scripts",
    "isort --diff scripts",
    "prettier --check scripts/x.js",
    "eslint scripts/x.js",
    "gofmt scripts/x.go",
    "shfmt scripts/x.sh",
    "yapf scripts/x.py",
    "autopep8 scripts/x.py",
    "python3 -m black --check scripts",
    "uv run black --check scripts",
    "uvx ruff format --check scripts",
    "uv run --with ruff ruff format --check scripts",
    "uv run --with ruff ruff format /tmp/x.py",
    "sed -i -e 's/a/b/' /tmp/outside.py",
    "perl -i -e 's/a/b/' /tmp/outside.py",
    "sed -i --expression='s/a/b/' /tmp/outside.py",
    "sed -i -e's/a/b/' /tmp/outside.py",
    "perl -i -Es/a/b/ /tmp/outside.py",
    "perl -pi -E 's/a/b/' /tmp/outside.py",
    "python3 scripts/daily_context.py --json --offline --out /tmp/probe.json",
    "uv run scripts/foo.py --output=/tmp/x.json",
    "python3 scripts/foo.py list -o /tmp/x.json",
    "python3 scripts/foo.py -vo /tmp/x.json",
    "python3 scripts/foo.py -vo=/tmp/x.json",
    "python3 scripts/foo.py -vo/tmp/x.json",
    "python3 scripts/foo.py -v list",
    "X=--output=/tmp/p; git diff $X",
    'REV=HEAD; git show "$REV":a.py',
    'N=3; git log -n "$N"',
    # a substitution the shell never runs is data
    "grep -n '`git reset --hard`' README.md",
    "echo '\\$(git reset --hard)'",
    "echo '$(git reset --hard)'",
    "grep -rn '$(git reset --hard)' docs",
    "printf '%s\\n' '`rm scripts/a.py`'",
    'echo "it\'s fine"; git log -1',
    'git log --since="$SINCE"',
    "python3 -c 'print(1)'; python3 -c 'print(2)'",
    "python3 -c 'print(1)' && node -e \"console.log(1)\"",
    "python3 -c 'print(\"cost is $5\")'",
    "python3 -c 'import re; print(re.match(r\"^a$\", \"a\"))'",
    "python3 -c \"import importlib.util as u; spec = u.spec_from_file_location('m', 'scripts/x.py'); m = u.module_from_spec(spec); spec.loader.exec_module(m)\"",
    "python3 -c \"executor(1); spawn_worker(2)\"",
    'python3 -c "import tempfile\nfrom pathlib import Path\nwith tempfile.TemporaryDirectory() as tmp:\n    p = Path(tmp) / \'probe.md\'\n    p.write_text(\'x\')"',
    "python3 -c \"import os; base = '/tmp'; p = os.path.join(base, 'x.py'); os.remove(p)\"",
    "python3 -c \"import subprocess; subprocess.run(['git', 'log', '--author=' + who])\"",
    "uv run ruff format --diff scripts",
    "biome format --write /tmp/outside/file.js",
    "biome format --check scripts/x.js",
    "biome lint scripts/x.js",
    'python3 -c "import tempfile\nwith tempfile.TemporaryDirectory() as tmp:\n    open(tmp + \'/x.txt\', \'w\').write(\'x\')"',
    'python3 -c "import tempfile\nwith tempfile.NamedTemporaryFile(\'w\') as t:\n    t.write(\'x\')"',
    "sed --in-place=.bak 's/a/b/' /tmp/x",
    "python3 -c \"import os; os.open('scripts/x.py', os.O_RDONLY)\"",
    "git -C /tmp diff --output=patch.diff",
    "ruby -e \"File.write '/tmp/x', 'x'\"",
    "perl -e 'unlink \"/tmp/x\"'",
    "ruby -e \"puts File.read 'scripts/x.rb'\"",
    "perl -e 'open(FH, \"<scripts/x.pl\"); print <FH>'",
    "ruby -e \"FileUtils.cp 'scripts/x.rb', '/tmp/x.rb'\"",
    "python3 -c \"import os; os.remove(os.path.join('/tmp', 'a', 'b'))\"",
    "perl -e 'open FH, \"<scripts/x.pl\"; print <FH>'",
    "python3 -c \"from pathlib import Path; print(Path('scripts/a').read_text().replace('a', 'b'))\"",
    "python3 -c \"from pathlib import Path; s = Path('scripts/a').read_text(); print(s.replace('a', 'b'))\"",
    "python3 -c \"from pathlib import Path; print(Path('/tmp/a').read_text().replace('a', 'b'))\"",
    "python3 -c \"from pathlib import Path; print(Path('scripts/a').name.replace('a', 'b'))\"",
    "python3 -c \"print(str(1).replace('1', '2'))\"",
    "cat <<'EOF'\n$(git reset --hard)\nEOF",
    'cat <<"EOF"\n$(git reset --hard)\nEOF',
    "cat <<EOF\n$(git log -1)\nEOF",
    "cat <<EOF\nplain $HOME text\nEOF",
    "cat <<EOF\nescaped \\$(git reset --hard)\nEOF",
    "python3 -c \"from pathlib import Path; p = Path('/tmp/x'); p.unlink(); p = Path('scripts/x.py'); print(p.read_text())\"",
    "python3 -c \"from pathlib import Path; p = Path('scripts/x.py'); print(p.read_text()); p = Path('/tmp/x'); p.unlink()\"",
    'python3 -c "from pathlib import Path\np = Path(\'/tmp/x\')\np.unlink()\np = Path(\'/tmp/y\')\np.unlink()"',
    'python3 -c "from pathlib import Path\nfor name in [\'a\', \'b\']:\n    p = Path(\'/tmp\') / name\n    print(p.read_text())"',
    'python3 -c "from pathlib import Path\nif c:\n    p = Path(\'/tmp/a\')\nelse:\n    q = Path(\'/tmp/b\')\np.unlink()"',
    'python3 -c "from pathlib import Path\np = Path(\'scripts/x.py\')\nprint(p.read_text())\np = Path(\'/tmp/x\')\np.unlink()"',
    "python3 --version",
    "node --version",
    "python3 -V",
    "uv run scripts/semantic.py query 'x' --limit 5",
    "git log < /tmp/in",
    "git diff 0</dev/null",
    "git log 3>&2",
    "python3 -m json.tool < scripts/a.json",
    "python3 -c 'import sys; print(sys.stdin.read())' < scripts/a.py",
    "python3 scripts/foo.py < /tmp/data",
    "python3 <<< 'print(1)'",
    "wc -l < scripts/a.py",
    "sort <scripts/a.py",
    "grep -c x 0< scripts/a.py",
    "cat <<< hello",
    "echo 0 < scripts/a.py",
    "tr a-z A-Z < scripts/a.py > /tmp/out",
    "sh <<< 'git status --short'",
    "cat script.sh | bash<<<'git status --short'",
    "git 2>/dev/null log -1",
    "git >/tmp/o status --short",
    "python3 2>/dev/null -c 'print(1)'",
    "python3 >/tmp/o scripts/foo.py",
    "git log >&/tmp/o",
    "python3 -c \"import os; os.remove(Path('/tmp/x.py'))\"",
    "python3 -c \"import shutil; shutil.copy('scripts/a.py', Path('/tmp/a.py'))\"",
    "python3 -c \"import os; os.remove(os.path.join('/tmp', 'x.py'))\"",
    "python3 -c \"open(Path('scripts/x.py')).read()\"",
    "python3 -c \"open(Path('scripts/x.py'), 'rb').read()\"",
    "python3 -c \"import subprocess; subprocess.run(['ls', d])\"",
    "python3 -c \"import subprocess; subprocess.run([sys.executable, '-c', 'print(1)'])\"",
    "python3 -c \"import asyncio; asyncio.run(main())\"",
    "python3 -c \"import subprocess; subprocess.run(['git', 'log', '-1']); note = run('git reset --hard')\"",
    "python3 -c \"import unittest; unittest.TestCase().run(); app.run(host)\"",
    "python3 -c \"import os; os.remove(os.path.join('/tmp', 'scripts/x.py'))\"",
    'python3 -c "import os\nprint(os.getcwd())"',
    'git log --format="%h\n%s" -1',
    'sh -c "echo hi\ngit log -1"',
    "bash<<EOF\ngit log -1\nEOF",
    "cat<<EOF\nhello\nEOF",
    'python3<<EOF\nprint(open("scripts/a.py").read())\nEOF',
    "python3 -c \"import subprocess; subprocess.run(['git', 'log', '--format=%s'])\"",
    "python3 -c \"import subprocess; subprocess.run(['git', 'log', '-1'], check=True, cwd=repo)\"",
    "node -e \"require('child_process').execFileSync('git', ['log', '-1'])\"",
    "node -e \"fs.renameSync('/tmp/a', '/tmp/b')\"",
    "node -e \"fs.copyFileSync('scripts/x.js', '/tmp/x.js')\"",
    "node -e \"console.log(fs.readFileSync('scripts/x.js', 'utf8'))\"",
    "node -e \"fs.rmSync('/tmp/x')\"",
    "node -e \"fs.openSync('scripts/x.js', 'r')\"",
    "node -e \"console.log(fs.existsSync('scripts/x.js'))\"",
    "node -e \"const {readFileSync} = require('fs'); console.log(readFileSync('scripts/x.js', 'utf8'))\"",
    "node -e \"const fsPromises = require('fs').promises; fsPromises.rm('/tmp/x')\"",
    "python3 -c \"from subprocess import run as r; r(['git', 'log', '-1'])\"",
    "python3 -c \"import notsubprocess; notsubprocess.run(['git', 'reset', '--hard'])\"",
    "python3 -c \"rm = lambda x: None; rm('scripts/x.py')\"",
    "node -e \"function cp(a, b) { return a + b; } console.log(cp('scripts/x.js', 'ignored')); const fs = require('fs'); console.log(fs.readFileSync('scripts/x.js', 'utf8'));\"",
    "python3 -c \"from os import remove as delete_file; delete_file('/tmp/x.py')\"",
    "node -e \"const {rm: removeIt} = require('fs'); removeIt('/tmp/x')\"",
    "python3 - <<'EOF'\nfrom subprocess import (\n    run as r,\n)\nr(['git', 'log', '-1'])\nEOF",
    "python3 -c \"f = open; print(f('scripts/x.py').read())\"",
    "python3 -c \"print('hello'.replace('h', 'H'))\"",
    "python3 -c \"import sys; sys.stdout.write('x')\"",
    "python3 -c \"import sys; sys.stderr.write('scripts/x.py')\"",
    "python3 -c \"f = open('/tmp/x', 'w'); f.write('x')\"",
    "python3 -c \"with open('/tmp/x', 'w') as f: f.write('scripts/x.py')\"",
    "python3 -c \"import io; buf = io.StringIO(); buf.write('x')\"",
    "python3 -c \"import tempfile; t = tempfile.NamedTemporaryFile('w'); t.write('x')\"",
    "python3 -c \"import tempfile, os; d = tempfile.mkdtemp(); open(os.path.join(d, 'x'), 'w')\"",
    "python3 -c \"from pathlib import Path; p = Path('/tmp/x'); p.rename('/tmp/y')\"",
    "python3 -c \"from pathlib import Path; p = '/tmp/x'; Path(p).write_text('x')\"",
    'python3 -c "def rename(a, b):\n    return a + b\nprint(rename(\'x\', \'y\'))"',
    'python3 -c "def remove(item): print(item)\nremove(\'scripts/x.py\')"',
    'python3 -c "import subprocess\nsp = subprocess\nsp.run([\'git\', \'log\', \'-1\'])"',
    'python3 -c "import os\nd = os.remove\ne = d\ne(\'/tmp/x.py\')"',
    "python3 -c \"from os import system as s; s('git log -1')\"",
    "python3 scripts/semantic.py query \"open('scripts/x.py','w')\"",
    "python3 -m json.tool \"open('scripts/x.py','w')\"",
    "python3 -c 'print(1)' \"open('scripts/x.py','w')\"",
    "node -r esm scripts/x.js",
    "perl -pe \"s/a/b/\" scripts/a.py",
    "bash -c 'python3 -c \"print(1)\"'",
    "echo '(a)' \"(b)\"",
    "node -e \"const fs = require('fs'); function cp(a, b) { return a + b } const other = cp; console.log(other('README.md', 'scripts/pwn.js')); console.log(fs.readFileSync('scripts/x.js', 'utf8'))\"",
    # a declaration is not a call, even of a shadowed name; argv is data
    'python3 -c "def remove(item):\n    return item\nfrom os import remove\nremove(\'/tmp/outside.py\')"',
    "node -e \"function unlink(a) { return a } const {unlink} = require('fs'); unlink('/tmp/outside.js')\"",
    'python3 -c "from subprocess import run\ndef run(cmd):\n    pass\nrun([\'echo\', \'hi\'])"',
    "python3 scripts/foo.py \"os.system('git reset --hard')\"",
    "python3 scripts/foo.py --grep \"subprocess.run(['git', 'reset', '--hard'])\"",
    "python3 -c '# uses subprocess to avoid calling git reset --hard directly'",
    "python3 - <<'EOF'\nDENIED = ('do shell script \"git reset --hard\"',)\nprint(DENIED)\nEOF",
    "python3 -c 'print(\"subprocess is how you would run git reset\")'",
    "python3 -c \"open('scripts/x.py').read()\"",
    "python3 -c \"open('scripts/x.py').read().count('x')\"",
    "python3 -c\"print(open('scripts/x.py').read())\"",
    "rg python3 /tmp/log",
    "echo python3",
    "grep -rn node scripts | head",
    "python3.13 scripts/harness_lint.py --json",
    "python3 -mjson.tool /tmp/x.json",
    "python3.12 -c \"print(1)\"",
    "rg python3.13 /tmp/log",
    "python3 -c \"open(file='scripts/x.py', mode='r').read()\"",
    "python3 -c \"import shutil; shutil.copy(src='scripts/x.py', dst='/tmp/a.py')\"",
    'X=/tmp; X=scripts echo x > "$X/a.py"',
    "python3 -c \"from pathlib import Path; p = Path('/tmp/x'); p.write_text('scripts/x.py')\"",
    "grep -n \"stray \\` backtick only\" README.md",
    "grep -n 'a `code` span' README.md",
    "grep -n '$(literal)' README.md",
    "rg -n 'open\\(' scripts",
    "python3 scripts/lint.py",
    "python3 -m unittest tests.test_git_retry",
    "python3 -c \"open('README.md').read(); open('scripts/x.py').read()\"",
    "python3 -c \"print(len(open('scripts/x.py', 'rb').read()))\"",
    "python3 -c \"print(len(open('scripts/x.py', 'rt').read()))\"",
    "python3 -c \"print(len(open('scripts/x.py', 'br').read()))\"",
    "python3 -c \"import subprocess; subprocess.run(['git', 'log', '-1'])\"",
    "python3 -c \"import subprocess; subprocess.run('cp README.md /tmp/r.md', shell=True)\"",
    "tar -tf /tmp/a.tar",
    "tar -cf /tmp/out.tar -C scripts readonly_bash_guard.py",
    "tar --create --file=/tmp/out.tar --directory=scripts readonly_bash_guard.py",
    "sudo -u root git log -1",
    "timeout 30 git log -1",
    "tar -czf /tmp/out.tgz scripts",
    "tar -xf /tmp/a.tar -C /tmp/out",
    "tar -xOf /tmp/a.tar README.md | head",
    "zip /tmp/out.zip README.md",
    "unzip -l /tmp/a.zip",
    "unzip /tmp/a.zip -d /tmp/out",
    "gzip -c README.md > /tmp/r.gz",
    "gzip -t /tmp/r.gz",
    "gunzip -c /tmp/r.gz | head",
    "tar --remove-files -cf /tmp/out.tar /tmp/x.py",
    "zip -m /tmp/out.zip /tmp/x.py",
    "rsync --remove-source-files /tmp/a.py /tmp/b.py",
    "git worktree list",
    "python3 - <<'EOF'\nimport subprocess\nsubprocess.run([\n    'git',\n    'log',\n])\nEOF",
    "python3 -c \"open('scripts/x.py', mode='r').read()\"",
    "python3 scripts/harness_lint.py",
    "uv run scripts/semantic.py query 'x'",
    "python3 -m json.tool /tmp/x.json",
    "tar tf /tmp/a.tar",
    "tar xf /tmp/a.tar -C /tmp/out",
    "curl -s https://example.com/",
    "curl -o /tmp/x.py https://example.com/x.py",
    "wget -O - https://example.com/ | head",
    "wget -O /tmp/x.py https://example.com/x.py",
    "wget -P /tmp https://example.com/x.py",
    "curl -Lo /tmp/x.py https://example.com/x.py",
    "curl -sL https://example.com/ | head",
    "wget -qO- https://example.com/ | head",
    "wget -qO /tmp/x.py https://example.com/x.py",
    ": <> /tmp/probe.txt",
    "grep -c x <scripts/x.py",
    "awk '{print $1}' scripts/x.py",
    "gawk -i inplace '{print}' /tmp/x.txt",
    "awk 'BEGIN{print \"x\" > \"/tmp/out.txt\"}'",
    "awk '{print $1 > \"/tmp/out\"}' /tmp/in",
    "sed -n 'w /tmp/x.txt' README.md",
    "sed 's/e/E/g' README.md",
    "sed -n '/end/p' README.md",
    "awk 'BEGIN{system(\"git \" \"log -1\")}'",
    "xargs python3 -c \"print(open('scripts/x.py').read())\"",
    "python3 -c \"from pathlib import Path; Path('scripts/x.py').open().read()\"",
    "python3 -c \"from pathlib import Path; Path('/tmp/x').open(mode='w').write('x')\"",
    "python3 -c \"DOC = 'example: os.system(\\\"git reset --hard\\\")'\"",
    "tar cf - README.md | wc -c",
    "tar cf - README.md | gzip -c > /tmp/out.tar.gz",
    "python3 scripts/render_runtime_edges.py --runtime codex --check",
    "python3 scripts/harness_lint.py --json",
    "python3 scripts/recurring.py list",
    "python3 scripts/privacy_check.py --json",
    "uv run scripts/recurring.py list",
    "uv run scripts/semantic.py query 'x' --limit 5",
    "uv run scripts/privacy_check.py --json",
    "python3 -m scripts.recurring list",
    "uv run --directory /repo scripts/recurring.py list",
    "uvx ruff check scripts",
    "uvx ruff check scripts tests --select F,E4,E7,E9,EXE001",
    "true; ./scripts/recurring.py list",
    "uv run python - <<'EOF'\nprint(1)\nEOF",
    "python3 -m unittest tests.test_git_retry",
    "git diff > /tmp/patch.diff",
    "git show HEAD:scripts/x.py > /tmp/x.py",
    "git log -1 2>/dev/null",
    "git hash-object scripts/x.py",
    "python3 -c \"open('/tmp/scratch', 'w').write('see README.md and scripts/x.py')\"",
    "python3 -c \"from pathlib import Path; Path('/tmp/x').write_text('scripts/x.py')\"",
    "python3 -c \"import shutil; shutil.copy('scripts/x.py', '/tmp/x.py')\"",
    "python3 -c \"import os; os.rename('/tmp/a', '/tmp/b')\"",
    "python3 -c \"import os; os.unlink('/tmp/a.py')\"",
    "python3 - <<'EOF'\nfrom pathlib import Path\np = Path('/tmp/x.py')\np.write_text('scripts/x.py')\nEOF",
    "python3 - <<'EOF'\nfrom pathlib import Path\np = Path('scripts/x.py')\nprint(p.read_text())\nEOF",
    "echo x&>/tmp/a.txt",
    "python3 -c \"import subprocess; subprocess.run(('git', 'log', '-1'))\"",
    "python3 - <<'EOF'\nCASES = [\"shutil.move('scripts/x.py', '/tmp/x')\", \"os.unlink('scripts/x.py')\"]\nprint(len(CASES))\nEOF",
    "python3 -c \"print(open('scripts/x.py', 'r').read())\"",
    "python3 -c \"open('/tmp/x.py', 'w').write('x')\"",
    "python3 - <<'EOF'\nfrom pathlib import Path\nprint(Path('scripts/x.py').read_text())\nEOF",
    "python3 -c \"import json; print(json.dumps({'write_text': 'scripts/x.py'}))\"",
    "echo {a,b}",
    "git log --format='{%h,%s}' -n 3",
)


class BlockedSubcommandsTest(unittest.TestCase):
    def test_worktree_moves_are_found(self) -> None:
        for command in DENIED:
            self.assertTrue(guard.blocked_subcommands(command), command)

    def test_reads_pass(self) -> None:
        for command in ALLOWED:
            self.assertEqual(guard.blocked_subcommands(command), [], command)

    def test_unbalanced_quotes_still_scan(self) -> None:
        self.assertEqual(guard.blocked_subcommands("git stash 'oops"), ["stash"])

    def test_unreadable_shell_input_is_named_unscannable_once(self) -> None:
        for command in ('eval "$CMD"', "bash x.sh", "bash < script.sh", "cat x.sh | bash"):
            self.assertEqual(guard.blocked_subcommands(command), [guard.UNSCANNABLE], command)

    def test_interpreter_text_is_matched_only_when_shelling_out(self) -> None:
        self.assertEqual(guard.blocked_subcommands("python3 -c \"os.system('git reset')\""), ["reset"])
        self.assertEqual(guard.blocked_subcommands("python3 -c \"print('git reset')\""), [])
        self.assertEqual(guard.blocked_subcommands("python3 -c \"subprocess.run(['reset', 'git'])\""), [])

    def test_brace_expansion_matches_the_shell(self) -> None:
        self.assertEqual(guard._brace_expand("a{b,c}d"), ["abd", "acd"])
        self.assertEqual(guard._brace_expand("x{,.bak}"), ["x", "x.bak"])
        self.assertEqual(guard._brace_expand("f{1..3}"), ["f1", "f2", "f3"])
        self.assertEqual(guard._brace_expand("{a,{b,c}}"), ["a", "b", "c"])
        for word in ("x{2}", "{}", "{print $1}", "a{b", "plain"):
            self.assertEqual(guard._brace_expand(word), [word], word)

    def test_joined_paths_follow_python_join_semantics(self) -> None:
        self.assertEqual(
            guard.blocked_subcommands(
                "python3 -c \"import os; os.remove(os.path.join('/tmp', '/repo/scripts/x.py'))\"", repo="/repo", cwd="/tmp"
            ),
            ["write:/repo/scripts/x.py"],
        )
        self.assertEqual(
            guard.blocked_subcommands(
                "python3 -c \"from pathlib import Path; import os; os.remove(Path('/tmp') / '/repo/scripts/x.py')\"", repo="/repo", cwd="/tmp"
            ),
            ["write:/repo/scripts/x.py"],
        )
        self.assertEqual(
            guard.blocked_subcommands("python3 -c \"import os; os.remove(os.path.join('/repo', '/tmp/x.py'))\"", repo="/repo", cwd="/tmp"),
            [],
        )
        # components after the absolute head are kept
        self.assertEqual(
            guard.blocked_subcommands("python3 -c \"import os; os.remove(os.path.join('/', 'repo', 'scripts/x.py'))\"", repo="/repo", cwd="/tmp"),
            ["write://repo/scripts/x.py"],
        )
        self.assertEqual(
            guard.blocked_subcommands(
                "python3 -c \"from pathlib import Path; (Path('/') / 'repo' / 'scripts/x.py').unlink()\"", repo="/repo", cwd="/tmp"
            ),
            ["write://repo/scripts/x.py"],
        )
        # a formatted literal is not a spelled-out path, wherever the cwd is
        self.assertEqual(
            guard.blocked_subcommands("python3 -c \"d = '/repo/scripts'; open(f'{d}/x.py', 'w')\"", repo="/repo", cwd="/tmp"),
            ["unscannable"],
        )

    def test_git_dash_c_moves_where_relative_paths_resolve(self) -> None:
        self.assertEqual(
            guard.blocked_subcommands("cd /tmp && git -C /repo diff --output=patch.diff", repo="/repo", cwd="/repo"),
            ["write:patch.diff"],
        )
        self.assertEqual(
            guard.blocked_subcommands(
                'cd /tmp && git -C "$CLAUDE_PROJECT_DIR" diff --output=patch.diff', repo="/repo", cwd="/repo", env={"CLAUDE_PROJECT_DIR": "/repo"}
            ),
            ["write:patch.diff"],
        )
        self.assertEqual(guard.blocked_subcommands("git -C /tmp diff --output=patch.diff", repo="/repo", cwd="/repo"), [])
        self.assertEqual(
            guard.blocked_subcommands('ARGS=--output=scripts/p.patch; git diff "$ARGS"', repo="/repo", cwd="/repo", env={}),
            ["write:scripts/p.patch"],
        )
        self.assertEqual(guard.blocked_subcommands('git -C "$X" diff --output=patch.diff', repo="/repo", cwd="/repo", env={}), ["unscannable"])
        self.assertEqual(
            guard.blocked_subcommands("cd /tmp && git -C /repo -c core.pager='tee out.txt' log -1", repo="/repo", cwd="/repo"),
            ["write:out.txt"],
        )

    def test_editor_targets_skip_flag_values(self) -> None:
        self.assertEqual(
            guard.blocked_subcommands("vim -Nu NONE -n -es scripts/x.py", repo="/repo", cwd="/repo"),
            ["write:scripts/x.py"],
        )
        self.assertEqual(guard.blocked_subcommands("ed -p '*' scripts/x.py", repo="/repo", cwd="/repo"), ["write:scripts/x.py"])
        self.assertEqual(
            guard.blocked_subcommands("vim -s/tmp/keys.txt scripts/x.py /tmp/other", repo="/repo", cwd="/repo"),
            ["unscannable"],  # the attached script is judged first and the scan stops at the first hit
        )
        self.assertEqual(
            guard.blocked_subcommands("python3 -c \"from pathlib import Path; Path('/repo/x').open(mode='w').write(1)\"", repo="/repo"),
            ["write:/repo/x"],
        )
        self.assertEqual(
            guard.blocked_subcommands("python3 -c \"open('/repo/x', 'w').write('y')\"", repo="/repo"),
            ["write:/repo/x"],
        )
        self.assertEqual(
            guard.blocked_subcommands("python3 -c \"from pathlib import Path; Path('/repo/a').open(mode='/tmp/x').write_text('y')\"", repo="/repo"),
            ["write:/repo/a"],
        )
        self.assertEqual(guard.blocked_subcommands("perl -e 'open(FH, \">scripts/x.pl\")'", repo="/repo", cwd="/repo"), ["write:scripts/x.pl"])
        self.assertEqual(guard.blocked_subcommands("python3 -c \"open(s, 'w').write('x')\"", repo="/repo", cwd="/repo"), ["unscannable"])
        self.assertEqual(guard.blocked_subcommands("sed -i -e 's/a/b/' scripts/x.py", repo="/repo", cwd="/repo"), ["write:scripts/x.py"])
        self.assertEqual(
            guard.blocked_subcommands("perl -i -Es/a/b/ scripts/x.py scripts/y.py", repo="/repo", cwd="/repo"), ["write:scripts/x.py"]
        )
        self.assertEqual(guard.blocked_subcommands("uv run --with ruff ruff format scripts", repo="/repo", cwd="/repo"), ["write:scripts"])
        self.assertEqual(
            guard.blocked_subcommands("python3 -c \"from pathlib import Path; Path('scripts/x').with_suffix('.bak').write_text('y')\"", repo="/repo", cwd="/repo"),
            ["write:scripts/x"],
        )
        self.assertEqual(
            guard.blocked_subcommands("perl -e 'open(FH, \">\", \"scripts/x.pl\")'", repo="/repo", cwd="/repo"), ["write:scripts/x.pl"]
        )
        self.assertEqual(
            guard.blocked_subcommands("python3 -c \"from pathlib import Path; (Path('/tmp') / 'repo' / 'x').write_text('y')\"", repo="/repo"),
            [],
        )

    def test_grouping_leaves_quoted_parentheses_alone(self) -> None:
        self.assertEqual(
            guard._tokens(guard._grouped("echo '(a)' (b)")),
            ["echo", "(a)", guard._SUBSHELL_OPEN, "b", guard._SUBSHELL_CLOSE],
        )

    def test_descriptor_prefixes_split_like_the_shell(self) -> None:
        self.assertEqual(guard._tokens("echo x2>f"), ["echo", "x2", ">f"])
        self.assertEqual(guard._tokens("git log 2>&1"), ["git", "log", "2>&1"])
        self.assertEqual(guard._tokens("cmd 0<> f"), ["cmd", "0<>", "f"])
        self.assertEqual(guard._tokens("cmd 2>>f"), ["cmd", "2>>f"])
        self.assertEqual(guard._tokens("a=1>f"), ["a=1", ">f"])
        self.assertEqual(guard._tokens("bash<<EOF"), ["bash", "<<EOF"])
        self.assertEqual(guard._tokens("cat<<<word"), ["cat", "<<<", "word"])

    def test_unscannable_is_reported_once_per_line(self) -> None:
        self.assertEqual(guard.blocked_subcommands("bash x.sh && bash y.sh"), [guard.UNSCANNABLE])
        self.assertEqual(len(guard.blocked_subcommands("bash x.sh\nbash y.sh")), 2)

    def test_awk_in_place_names_the_file_not_the_program(self) -> None:
        self.assertEqual(
            guard.blocked_subcommands("gawk -i inplace -e '{print}' scripts/x.py", repo="/repo", cwd="/repo", env={}),
            ["write:scripts/x.py"],
        )

    def test_writes_name_their_target_and_the_repo_root_is_honoured(self) -> None:
        self.assertEqual(guard.blocked_subcommands("echo x > scripts/a.py", repo="/repo"), ["write:scripts/a.py"])
        self.assertEqual(guard.blocked_subcommands("echo x >| scripts/a.py", repo="/repo"), ["write:scripts/a.py"])
        self.assertEqual(guard.blocked_subcommands("echo x >>scripts/a.py", repo="/repo"), ["write:scripts/a.py"])
        self.assertEqual(guard.blocked_subcommands("echo x > /repo/scripts/a.py", repo="/repo"), ["write:/repo/scripts/a.py"])
        self.assertEqual(guard.blocked_subcommands("echo x > /elsewhere/a.py", repo="/repo"), [])
        # ~ expands from HOME; an unknown HOME makes the target unscannable
        self.assertEqual(guard.blocked_subcommands("echo x > ~/repo/a.py", repo="/home/u/repo", cwd="/tmp", env={"HOME": "/home/u"}), ["write:~/repo/a.py"])
        self.assertEqual(guard.blocked_subcommands("echo x > ~/other/a.py", repo="/home/u/repo", cwd="/tmp", env={"HOME": "/home/u"}), [])
        self.assertEqual(guard.blocked_subcommands("echo x > ~/a.py", repo="/repo", cwd="/repo", env={}), [guard.UNSCANNABLE])
        # a prefix assignment scopes to its command and does not change the same line's expansion
        self.assertEqual(
            guard.blocked_subcommands('CLAUDE_PROJECT_DIR=/tmp echo x > "$CLAUDE_PROJECT_DIR/scripts/a.py"', repo="/repo", cwd="/repo", env={"CLAUDE_PROJECT_DIR": "/repo"}),
            ["write:$CLAUDE_PROJECT_DIR/scripts/a.py"],
        )
        # PWD follows cd
        self.assertEqual(guard.blocked_subcommands('cd /repo && echo x > "$PWD/a.py"', repo="/repo", cwd="/tmp", env={}), ["write:$PWD/a.py"])
        self.assertEqual(guard.blocked_subcommands('cd /tmp && echo x > "$PWD/a.py"', repo="/repo", cwd="/repo", env={}), [])
        # a tilde stored in a variable expands at assignment time
        self.assertEqual(guard.blocked_subcommands('T=~; echo x > "$T/a.py"', repo="/repo", cwd="/tmp", env={"HOME": "/repo"}), ["write:$T/a.py"])
        self.assertEqual(guard.blocked_subcommands('T=~; echo x > "$T/a.py"', repo="/repo", cwd="/tmp", env={"HOME": "/home/u"}), [])
        # assignments apply in execution order
        self.assertEqual(
            guard.blocked_subcommands('A=/tmp; echo x > "$A/first"; A=scripts; echo x > "$A/second"', repo="/repo", cwd="/repo", env={}),
            ["write:$A/second"],
        )
        # variables resolve from the given environment; PWD is the cwd
        self.assertEqual(
            guard.blocked_subcommands('cp /tmp/a "$P/scripts/a.py"', repo="/repo", cwd="/repo", env={"P": "/repo"}),
            ["write:$P/scripts/a.py"],
        )
        self.assertEqual(guard.blocked_subcommands('cp /tmp/a "$P/a.py"', repo="/repo", cwd="/repo", env={"P": "/elsewhere"}), [])
        self.assertEqual(guard.blocked_subcommands('cp /tmp/a "$PWD/a.py"', repo="/repo", cwd="/repo/sub", env={}), ["write:$PWD/a.py"])
        self.assertEqual(guard.blocked_subcommands('cp /tmp/a "$Q/a.py"', repo="/repo", cwd="/repo", env={}), [guard.UNSCANNABLE])
        # relative paths resolve from cwd, so ../ can leave or stay inside the repo
        self.assertEqual(guard.blocked_subcommands("echo x > ../outside.txt", repo="/repo", cwd="/repo"), [])
        self.assertEqual(guard.blocked_subcommands("echo x > ../a.py", repo="/repo", cwd="/repo/sub"), ["write:../a.py"])
        # a checkout under a scratch root is still the repository
        self.assertEqual(guard.blocked_subcommands("echo x > /tmp/atelier/scripts/a.py", repo="/tmp/atelier"), ["write:/tmp/atelier/scripts/a.py"])
        self.assertEqual(guard.blocked_subcommands("echo x > /tmp/other/a.py", repo="/tmp/atelier"), [])

    def test_every_segment_is_scanned(self) -> None:
        self.assertEqual(guard.blocked_subcommands("git log -1 && git reset --hard; git tag v2"), ["reset", "tag"])


class DecideTest(unittest.TestCase):
    def test_repo_writes_get_their_own_reason(self) -> None:
        decision = guard.decide({"tool_name": "Bash", "tool_input": {"command": "sed -i 's/a/b/' scripts/x.py"}, "cwd": str(ROOT)})
        self.assertIn("writes into the repository", decision["hookSpecificOutput"]["permissionDecisionReason"])
        self.assertIn("scripts/x.py", decision["hookSpecificOutput"]["permissionDecisionReason"])

    def test_unscannable_input_gets_its_own_reason(self) -> None:
        decision = guard.decide({"tool_name": "Bash", "tool_input": {"command": 'eval "$CMD"'}})
        self.assertIn("cannot resolve", decision["hookSpecificOutput"]["permissionDecisionReason"])

    def test_denies_with_a_reason_that_names_the_baseline_command(self) -> None:
        decision = guard.decide({"tool_name": "Bash", "tool_input": {"command": "git stash"}})
        self.assertIsNotNone(decision)
        out = decision["hookSpecificOutput"]
        self.assertEqual(out["hookEventName"], "PreToolUse")
        self.assertEqual(out["permissionDecision"], "deny")
        self.assertIn("git show <rev>:<path>", out["permissionDecisionReason"])

    def test_reads_and_other_tools_pass(self) -> None:
        self.assertIsNone(guard.decide({"tool_name": "Bash", "tool_input": {"command": "git diff"}}))
        self.assertIsNone(guard.decide({"tool_name": "Read", "tool_input": {"file_path": "x"}}))
        self.assertIsNone(guard.decide({"tool_input": {"command": "git status"}}))

    def test_uninterpretable_bash_payloads_are_denied_loudly(self) -> None:
        for payload in (None, [], {}, {"tool_input": None}, {"tool_name": "Bash", "tool_input": {"command": 3}}):
            decision = guard.decide(payload)
            self.assertIsNotNone(decision, payload)
            self.assertIn("no Bash command to inspect", decision["hookSpecificOutput"]["permissionDecisionReason"])


class MainTest(unittest.TestCase):
    def _run(self, stdin: str) -> tuple[int, str]:
        proc = subprocess.run(
            [sys.executable, str(ROOT / "scripts" / "readonly_bash_guard.py")],
            input=stdin,
            capture_output=True,
            text=True,
            timeout=30,
        )
        return proc.returncode, proc.stdout

    def test_deny_is_json_on_stdout_with_exit_zero(self) -> None:
        code, out = self._run(json.dumps({"tool_name": "Bash", "tool_input": {"command": "git reset --hard"}}))
        self.assertEqual(code, 0)
        self.assertEqual(json.loads(out)["hookSpecificOutput"]["permissionDecision"], "deny")

    def test_pass_is_silent(self) -> None:
        code, out = self._run(json.dumps({"tool_name": "Bash", "tool_input": {"command": "git show HEAD:a"}}))
        self.assertEqual((code, out), (0, ""))

    def test_unparseable_stdin_is_denied_with_exit_zero(self) -> None:
        for stdin in ("not json", ""):
            code, out = self._run(stdin)
            self.assertEqual(code, 0)
            self.assertEqual(json.loads(out)["hookSpecificOutput"]["permissionDecision"], "deny")

    def test_internal_failure_is_denied_with_exit_zero(self) -> None:
        def boom(payload: object) -> None:
            raise RuntimeError("boom")

        original = guard.decide
        guard.decide = boom
        sys.stdin = io.StringIO(json.dumps({"tool_input": {"command": "git log"}}))
        try:
            with redirect_stdout(io.StringIO()) as out:
                self.assertEqual(guard.main(), 0)
        finally:
            guard.decide = original
            sys.stdin = sys.__stdin__
        decision = json.loads(out.getvalue())["hookSpecificOutput"]
        self.assertEqual(decision["permissionDecision"], "deny")
        self.assertIn("RuntimeError", decision["permissionDecisionReason"])

    def test_main_in_process_writes_nothing_for_a_read(self) -> None:
        sys.stdin = io.StringIO(json.dumps({"tool_input": {"command": "git log"}}))
        try:
            with redirect_stdout(io.StringIO()) as out:
                self.assertEqual(guard.main(), 0)
        finally:
            sys.stdin = sys.__stdin__
        self.assertEqual(out.getvalue(), "")


if __name__ == "__main__":
    unittest.main()
