#!/usr/bin/env python3
"""Render provider-native edges from canonical skill and agent sources.

Run with ``--runtime all --check`` to detect drift or ``--apply`` to rewrite
derived files. Canonical behavior lives in ``skills/`` and ``agents/``;
runtime directories are never edited by hand.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

TIER_TO_EFFORT = {"light": "low", "balanced": "medium", "deep": "high", "xdeep": "xhigh"}

EXTRA_AGENT_LINES = {
    "forgetter": (
        "Return the decay-report envelope with the exact opening marker "
        "`---forgetter-result---` and closing marker `---end-result---`.\n"
    ),
}

# This project skill is handwritten and has no row in the public skill registry.
HAND_WRITTEN_SKILLS = {"atelier"}


def _load(name: str) -> dict:
    from registries import load_agents, load_models, load_skills

    return {
        "agents.toml": lambda: {"agents": load_agents(ROOT)},
        "models.toml": lambda: {"models": load_models(ROOT)},
        "skills.toml": lambda: {"skills": load_skills(ROOT)},
    }[name]()


def _read_source(row: dict, *, prefix: str, suffix: str) -> tuple[str, str]:
    source = str(row.get("source", ""))
    if not source.startswith(prefix) or not source.endswith(suffix):
        raise SystemExit(f"canonical source must match {prefix}<name>{suffix}: {source!r}")
    path = ROOT / source
    try:
        return source, path.read_text(encoding="utf-8")
    except OSError as exc:
        raise SystemExit(f"cannot read canonical source {source}: {exc}") from exc


def _frontmatter(text: str, source: str) -> str:
    if not text.startswith("---\n"):
        raise SystemExit(f"canonical source has no frontmatter: {source}")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise SystemExit(f"canonical source has unterminated frontmatter: {source}")
    return text[: end + 5]


def _skill_description(name: str, description: str) -> str:
    body = description.replace(" — ", ": ", 1)
    return (
        f"Run the Atelier `/{name}` workflow in Codex using the canonical public skill. "
        f"Use when the user explicitly invokes `${name}`. {body}"
    )


def render_claude(agents: dict, skills: dict, _models: dict) -> dict[Path, str]:
    files: dict[Path, str] = {}
    for name, row in sorted(agents.get("agents", {}).items()):
        if row.get("status") == "script-driven":
            continue
        source, content = _read_source(row, prefix="agents/", suffix=".md")
        files[ROOT / ".claude" / "agents" / f"{name}.md"] = (
            _frontmatter(content, source)
            + "\n<!-- GENERATED by scripts/render_runtime_edges.py; edit the canonical source. -->\n\n"
            + f"Read `CLAUDE.md` and `{source}` completely, then act as that role.\n"
        )
    for name, row in sorted(skills.get("skills", {}).items()):
        source, _content = _read_source(row, prefix="skills/", suffix="/SKILL.md")
        description = str(row.get("description", ""))
        files[ROOT / ".claude" / "commands" / f"{name}.md"] = (
            "---\n"
            f"description: {json.dumps(description, ensure_ascii=False)}\n"
            "---\n\n"
            "<!-- GENERATED by scripts/render_runtime_edges.py; edit the canonical source. -->\n\n"
            f"Read `{source}` completely and execute it. Treat text following `/{name}` as context or arguments.\n"
        )
    return files


def render_codex(agents: dict, skills: dict, models: dict) -> dict[Path, str]:
    files: dict[Path, str] = {}
    for key, row in sorted(agents.get("agents", {}).items()):
        if row.get("status") == "script-driven":
            continue
        source, _content = _read_source(row, prefix="agents/", suffix=".md")
        native = row.get("voices", {}).get("native")
        tier = models.get("models", {}).get(native, {}).get("reasoning_tier")
        effort = TIER_TO_EFFORT.get(tier)
        if effort is None:
            raise SystemExit(f"agent {key}: native voice {native!r} has no mapped reasoning_tier")
        description = str(row.get("description", ""))
        if '"' in description:
            raise SystemExit(f"agent {key}: description contains a double quote; extend the renderer")
        extra = EXTRA_AGENT_LINES.get(key, "")
        files[ROOT / ".codex" / "agents" / f"{key}.toml"] = (
            "# GENERATED by scripts/render_runtime_edges.py; edit agents/ and harness/agents.toml.\n"
            f'name = "{key}"\n'
            f'description = "{description}"\n'
            f'model_reasoning_effort = "{effort}"\n'
            'developer_instructions = """\n'
            f"Act as the Atelier `{key}` role for the bounded task delegated by the parent.\n"
            f"Before acting, read `CLAUDE.md` and `{source}`.\n"
            "Treat the canonical role as authoritative and translate Claude-specific tool names with `AGENTS.md`.\n"
            f"{extra}"
            "Return a concise result to the parent. Follow the role's write boundary and never take "
            "orchestrator-owned write, approval, or commit actions unless the role source explicitly assigns them.\n"
            '"""\n'
        )

    for name, row in sorted(skills.get("skills", {}).items()):
        if name in HAND_WRITTEN_SKILLS:
            continue
        source, _content = _read_source(row, prefix="skills/", suffix="/SKILL.md")
        description = str(row.get("description", ""))
        skill_dir = ROOT / ".agents" / "skills" / name
        files[skill_dir / "SKILL.md"] = (
            "---\n"
            f"name: {name}\n"
            f"description: {json.dumps(_skill_description(name, description), ensure_ascii=False)}\n"
            "---\n\n"
            "<!-- GENERATED by scripts/render_runtime_edges.py; edit the canonical source. -->\n\n"
            "## Atelier Skill\n\n"
            f"Run the explicit Codex `${name}` skill. Read `AGENTS.md`, `CLAUDE.md`, and `{source}` completely, "
            "then execute the canonical workflow in this thread. Treat following text as context or arguments. "
            "Do not start a nested Codex process.\n"
        )
        files[skill_dir / "agents" / "openai.yaml"] = (
            "# GENERATED by scripts/render_runtime_edges.py; edit harness/skills.toml and re-render.\n"
            "interface:\n"
            f'  display_name: "Atelier ${name}"\n'
            f'  short_description: "Run the Atelier ${name} skill in Codex"\n'
            f'  default_prompt: "Use ${name} to run the matching Atelier skill."\n\n'
            "policy:\n"
            "  allow_implicit_invocation: false\n"
        )
    return files


def render_all(agents: dict, skills: dict, models: dict) -> dict[Path, str]:
    return {**render_claude(agents, skills, models), **render_codex(agents, skills, models)}


RENDERERS = {"all": render_all, "claude": render_claude, "codex": render_codex}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runtime", required=True, choices=sorted(RENDERERS))
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--apply", action="store_true")
    args = parser.parse_args(argv)

    files = RENDERERS[args.runtime](_load("agents.toml"), _load("skills.toml"), _load("models.toml"))
    drift: list[str] = []
    for path, content in sorted(files.items()):
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current != content:
            drift.append(str(path.relative_to(ROOT)) + ("" if current is not None else " (missing)"))
            if args.apply:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")

    if args.apply:
        print(f"rendered {len(files)} files; rewrote {len(drift)}")
        return 0
    if drift:
        print(f"DRIFT: {len(drift)} of {len(files)} rendered files differ from disk:")
        for item in drift:
            print(f"  {item}")
        return 1
    print(f"clean: {len(files)} rendered files match disk byte-for-byte")
    return 0


if __name__ == "__main__":
    sys.exit(main())
