#!/usr/bin/env python3
"""Render runtime edges from the canonical harness registries.

Run with --runtime codex: --check exits 1 on drift; --apply writes the edges.
Check byte-for-byte parity before trusting apply. Hand-written Atelier skill
and .codex/hooks.json are excluded. Quirks belong in registry data or the
small runtime tables here, never hand-edited generated files.
Registry ownership and validation: harness/README.md.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

TIER_TO_EFFORT = {"light": "low", "balanced": "medium", "deep": "high", "xdeep": "xhigh"}

# Role-specific extra developer-instruction lines (inserted before the final
# boilerplate line). Mirrors harness_lint's codex-forgetter-envelope-drift.
EXTRA_AGENT_LINES = {
    "forgetter": (
        "Return the decay-report envelope with the exact opening marker "
        "`---forgetter-result---` and closing marker `---end-result---`.\n"
    ),
}

# Skills whose directory is hand-written and must never be rendered over.
HAND_WRITTEN_SKILLS = {"atelier"}


def _load(name: str) -> dict:
    # Delegate to the shared validated loaders; a registry problem surfaces as
    # one typed error here instead of a KeyError deep in a template.
    from registries import load_agents, load_commands, load_models

    return {
        "agents.toml": lambda: {"agents": load_agents(ROOT)},
        "commands.toml": lambda: {"commands": load_commands(ROOT)},
        "models.toml": lambda: {"models": load_models(ROOT)},
    }[name]()


def _skill_description(name: str, description: str) -> str:
    # Registry prose uses em dashes; the skill YAML register replaces the
    # first " — " with ": " (historical convention, kept for byte stability).
    body = description.replace(" — ", ": ", 1)
    return (
        f"Run the Atelier `/{name}` workflow in Codex using the shared "
        f"command registry. Use when the user explicitly invokes `${name}`. {body}"
    )


def render_codex(agents: dict, commands: dict, models: dict) -> dict[Path, str]:
    files: dict[Path, str] = {}

    for key, row in sorted(agents.get("agents", {}).items()):
        source = str(row.get("source", ""))
        if not source.startswith(".claude/agents/"):
            continue  # script-driven roles have no adapter
        native = row.get("voices", {}).get("native")
        tier = models.get("models", {}).get(native, {}).get("reasoning_tier")
        effort = TIER_TO_EFFORT.get(tier)
        if effort is None:
            raise SystemExit(f"agent {key}: native voice {native!r} has no mapped reasoning_tier")
        description = str(row.get("description", ""))
        if '"' in description:
            raise SystemExit(f"agent {key}: description contains a double quote; extend the renderer")
        extra = EXTRA_AGENT_LINES.get(key, "")
        files[ROOT / ".codex" / "agents" / f"{key}.toml"] = (
            "# GENERATED by scripts/render_runtime_edges.py from harness/*.toml; edit the registries and re-render.\n"
            f'name = "{key}"\n'
            f'description = "{description}"\n'
            f'model_reasoning_effort = "{effort}"\n'
            'developer_instructions = """\n'
            f"Act as the Atelier `{key}` role for the bounded task delegated by the parent.\n"
            f"Before acting, read `CLAUDE.md` and `{source}`.\n"
            "Treat the role source as authoritative and translate Claude-specific tool names with `AGENTS.md`.\n"
            f"{extra}"
            "Return a concise result to the parent. Follow the role's write boundary and never take "
            "orchestrator-owned write, approval, or commit actions unless the role source explicitly assigns them.\n"
            '"""\n'
        )

    for name, row in sorted(commands.get("commands", {}).items()):
        if row.get("user_facing", True) is False or name in HAND_WRITTEN_SKILLS:
            continue
        source = str(row.get("source", ""))
        description = str(row.get("description", ""))
        skill_dir = ROOT / ".agents" / "skills" / name
        files[skill_dir / "SKILL.md"] = (
            "---\n"
            f"name: {name}\n"
            f'description: "{_skill_description(name, description)}"\n'
            "---\n\n"
            "<!-- GENERATED by scripts/render_runtime_edges.py from harness/commands.toml; edit the registry and re-render. -->\n\n"
            "## Atelier Command\n\n"
            f"Run the explicit Codex `${name}` skill. Its authoritative workflow source is\n"
            f"the Claude Code `/{name}` command specification.\n\n"
            "1. Read `AGENTS.md` and `CLAUDE.md`.\n"
            f"2. Read the authoritative `{source}` command specification directly.\n"
            "3. Execute it in this thread using the Codex adaptation table in `AGENTS.md`.\n"
            f"4. Treat text following `${name}` as command context or arguments.\n"
            "5. Do not start a nested Codex process; complete the workflow in this thread.\n"
        )
        files[skill_dir / "agents" / "openai.yaml"] = (
            "# GENERATED by scripts/render_runtime_edges.py; edit harness/commands.toml and re-render.\n"
            "interface:\n"
            f'  display_name: "Atelier ${name}"\n'
            f'  short_description: "Run the Atelier ${name} skill in Codex"\n'
            f'  default_prompt: "Use ${name} to run the matching Atelier command."\n\n'
            "policy:\n"
            "  allow_implicit_invocation: false\n"
        )

    return files


RENDERERS = {"codex": render_codex}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runtime", required=True, choices=sorted(RENDERERS))
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--apply", action="store_true")
    args = parser.parse_args(argv)

    files = RENDERERS[args.runtime](_load("agents.toml"), _load("commands.toml"), _load("models.toml"))

    drift: list[str] = []
    for path, content in sorted(files.items()):
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current != content:
            drift.append(str(path.relative_to(ROOT)) + ("" if current is not None else " (missing)"))
            if args.apply:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")

    if args.apply:
        print(f"rendered {len(files)} files; rewrote {len(drift)}")
        return 0
    if drift:
        print(f"DRIFT: {len(drift)} of {len(files)} rendered files differ from disk:")
        for item in drift:
            print(f"  {item}")
        return 1
    print(f"clean: {len(files)} rendered files match disk byte-for-byte")
    return 0


if __name__ == "__main__":
    sys.exit(main())
